var searchData=
[
  ['name_0',['name',['../classgrpc__core_1_1_child_policy_handler.html#ab3565121b0734662b11b6e022bc53fad',1,'grpc_core::ChildPolicyHandler::name()'],['../classgrpc__core_1_1_load_balancing_policy.html#abddd9ff985719add0485224bfc9ae49c',1,'grpc_core::LoadBalancingPolicy::name()'],['../classgrpc__core_1_1_load_balancing_policy_factory.html#a4e266ad15247af4e929ef4fc7fe3e675',1,'grpc_core::LoadBalancingPolicyFactory::name()']]],
  ['name_20additionalimportdirs_20a_20additionalimportdirs_20setting_20location_20of_20imported_20tt_20proto_20tt_20files_1',['&lt;a name=&quot;AdditionalImportDirs&quot;&gt;&lt;/a&gt;AdditionalImportDirs - Setting location of imported &lt;tt&gt;.proto&lt;/tt&gt; files',['../md_src_2csharp_2_b_u_i_l_d-_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md48',1,'']]],
  ['name_20autoinclude_20a_20automatically_20including_20tt_20proto_20tt_20files_2',['&lt;a name=&quot;autoinclude&quot;&gt;&lt;/a&gt;Automatically including &lt;tt&gt;.proto&lt;/tt&gt; files',['../md_src_2csharp_2_b_u_i_l_d-_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md53',1,'']]],
  ['name_20compiler_20a_20bypassing_20grpc_20tools_20to_20run_20the_20protocol_20buffers_20compiler_20explicitly_3',['&lt;a name=&quot;compiler&quot;&gt;&lt;/a&gt;Bypassing Grpc.Tools to run the protocol buffers compiler explicitly',['../md_src_2csharp_2_b_u_i_l_d-_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md61',1,'']]],
  ['name_20grpcservices_20a_20grpcservices_20generating_20grpc_20services_20and_20protocol_20buffers_20messages_4',['&lt;a name=&quot;grpcservices&quot;&gt;&lt;/a&gt;GrpcServices - Generating gRPC services and protocol buffers messages',['../md_src_2csharp_2_b_u_i_l_d-_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md50',1,'']]],
  ['name_20nocompile_20a_20generate_20proto_20and_20grpc_20c_20sources_20from_20proto_20files_20no_20c_20compile_5',['&lt;a name=&quot;nocompile&quot;&gt;&lt;/a&gt;Generate proto and gRPC C# sources from .proto files (no C# compile)',['../md_src_2csharp_2_b_u_i_l_d-_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md55',1,'']]],
  ['name_20proto_20only_20nuget_20a_20including_20tt_20proto_20tt_20files_20in_20nuget_20packages_6',['&lt;a name=&quot;proto-only-nuget&quot;&gt;&lt;/a&gt;Including &lt;tt&gt;.proto&lt;/tt&gt; files in NuGet packages',['../md_src_2csharp_2_b_u_i_l_d-_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md65',1,'']]],
  ['name_20protoroot_20a_20protoroot_20common_20root_20for_20one_20or_20more_20tt_20proto_20tt_20files_7',['&lt;a name=&quot;ProtoRoot&quot;&gt;&lt;/a&gt;ProtoRoot - Common root for one or more &lt;tt&gt;.proto&lt;/tt&gt; files',['../md_src_2csharp_2_b_u_i_l_d-_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md45',1,'']]],
  ['name_20unsupported_20arch_20a_20using_20grpc_20tools_20with_20unsupported_20architectures_8',['&lt;a name=&quot;unsupported-arch&quot;&gt;&lt;/a&gt;Using Grpc.Tools with unsupported architectures',['../md_src_2csharp_2_b_u_i_l_d-_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md63',1,'']]],
  ['name_20visualstudio_20a_20visual_20studio_3a_20setting_20per_20file_20tt_20proto_20tt_20file_20options_9',['&lt;a name=&quot;visualstudio&quot;&gt;&lt;/a&gt;Visual Studio: setting per-file &lt;tt&gt;.proto&lt;/tt&gt; file options',['../md_src_2csharp_2_b_u_i_l_d-_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md57',1,'']]],
  ['named_5fmetrics_10',['named_metrics',['../structgrpc__core_1_1_backend_metric_data.html#a0f4d7d12badac03f290b3296f4aaf7dc',1,'grpc_core::BackendMetricData::named_metrics'],['../struct_backend_metric_data.html#a0f4d7d12badac03f290b3296f4aaf7dc',1,'BackendMetricData::named_metrics']]],
  ['naming_20for_20grpc_11',['Naming for GRPC',['..//Users/nikhil/Programming/GitHub/grpc/src/core/client_channel/README.md#autotoc_md6',1,'']]],
  ['native_20debug_12',['Using grpc-native-debug',['..//Users/nikhil/Programming/GitHub/grpc/src/ruby/nativedebug/README.md#autotoc_md170',1,'']]],
  ['native_20debug_20gem_13',['Finding the correct grpc-native-debug gem',['..//Users/nikhil/Programming/GitHub/grpc/src/ruby/nativedebug/README.md#autotoc_md171',1,'']]],
  ['nativednsresolver_14',['NativeDNSResolver',['../classgrpc__core_1_1_native_d_n_s_resolver.html',1,'grpc_core']]],
  ['negative_5fhttp2_5fclient_15',['negative_http2_client',['../namespacenegative__http2__client.html',1,'']]],
  ['nesteddefect_16',['NestedDefect',['../classtests_1_1unit_1_1framework_1_1common_1_1test__control_1_1_nested_defect.html',1,'tests::unit::framework::common::test_control']]],
  ['net_20build_17',['Protocol Buffers/gRPC Codegen Integration Into .NET Build',['../md_src_2csharp_2_b_u_i_l_d-_i_n_t_e_g_r_a_t_i_o_n.html',1,'']]],
  ['network_20transition_20behaviors_18',['Network Transition Behaviors',['../md_src_2objective-c_2_network_transition_behavior.html#autotoc_md93',1,'Expected Network Transition Behaviors'],['../md_src_2objective-c_2_network_transition_behavior.html',1,'gRPC iOS Network Transition Behaviors']]],
  ['networkerror_19',['NetworkError',['../classgrpc_1_1framework_1_1interfaces_1_1face_1_1face_1_1_network_error.html',1,'grpc::framework::interfaces::face::face']]],
  ['never_20',['Never',['../structgrpc__core_1_1_never.html',1,'grpc_core']]],
  ['newchttp2serverlistener_21',['NewChttp2ServerListener',['../classgrpc__core_1_1_new_chttp2_server_listener.html',1,'grpc_core']]],
  ['newconnectedsubchannel_22',['NewConnectedSubchannel',['../classgrpc__core_1_1_new_connected_subchannel.html',1,'grpc_core']]],
  ['newslicerefcount_23',['NewSliceRefcount',['../classgrpc__core_1_1_new_slice_refcount.html',1,'grpc_core']]],
  ['newwithlenslicerefcount_24',['NewWithLenSliceRefcount',['../classgrpc__core_1_1_new_with_len_slice_refcount.html',1,'grpc_core']]],
  ['next_25',['Next',['../classgrpc__core_1_1pipe__detail_1_1_next.html',1,'grpc_core::pipe_detail']]],
  ['next_26',['next',['../structgrpc__cq__completion.html#a0200fe183bf73662d9e64daadbafc546',1,'grpc_cq_completion']]],
  ['next_5fadjusted_5fkeepalive_5ftimestamp_27',['next_adjusted_keepalive_timestamp',['../structgrpc__chttp2__transport.html#ae66943e63dddfcd256ca3eb1667c7283',1,'grpc_chttp2_transport']]],
  ['next_5fcall_5fstack_28',['next_call_stack',['../structnext__call__stack.html',1,'']]],
  ['next_5fdata_29',['next_data',['../structgrpc__closure.html#a5ec102108f70b2c54f2495da0fee41d4',1,'grpc_closure']]],
  ['next_5fstream_5fid_30',['next_stream_id',['../structgrpc__chttp2__transport.html#a231411a065f1a2ddd864fd299f6dab36',1,'grpc_chttp2_transport']]],
  ['nextattemptdelay_31',['NextAttemptDelay',['../classgrpc__core_1_1_back_off.html#a494b6f389dba0aa38073f9f4a1d13041',1,'grpc_core::BackOff']]],
  ['nextmessage_32',['NextMessage',['../classgrpc__core_1_1filters__detail_1_1_next_message.html',1,'grpc_core::filters_detail']]],
  ['nextmessage_3c_20on_5fdone_20_3e_33',['NextMessage&lt; on_done &gt;',['../classgrpc__core_1_1filters__detail_1_1_next_message.html',1,'grpc_core::filters_detail']]],
  ['nextmessage_3c_26callstate_3a_3afinishpullclienttoservermessage_20_3e_34',['NextMessage&lt;&amp;CallState::FinishPullClientToServerMessage &gt;',['../classgrpc__core_1_1filters__detail_1_1_next_message.html',1,'grpc_core::filters_detail']]],
  ['nextmessage_3c_26callstate_3a_3afinishpullservertoclientmessage_20_3e_35',['NextMessage&lt;&amp;CallState::FinishPullServerToClientMessage &gt;',['../classgrpc__core_1_1filters__detail_1_1_next_message.html',1,'grpc_core::filters_detail']]],
  ['nextpromise_36',['NextPromise',['../classgrpc__core_1_1_reclaimer_queue_1_1_next_promise.html',1,'grpc_core::ReclaimerQueue']]],
  ['nextresult_37',['NextResult',['../classgrpc__core_1_1_inter_activity_pipe_1_1_next_result.html',1,'grpc_core::InterActivityPipe&lt; T, kQueueSize &gt;::NextResult'],['../classgrpc__core_1_1_next_result.html',1,'grpc_core::NextResult&lt; T &gt;']]],
  ['nextvaluetraits_38',['NextValueTraits',['../structgrpc__core_1_1for__each__detail_1_1_next_value_traits.html',1,'grpc_core::for_each_detail']]],
  ['nextvaluetraits_3c_20filters_5fdetail_3a_3anextmessage_3c_20on_5fprogress_20_3e_20_3e_39',['NextValueTraits&lt; filters_detail::NextMessage&lt; on_progress &gt; &gt;',['../structgrpc__core_1_1for__each__detail_1_1_next_value_traits_3_01filters__detail_1_1_next_message_3_01on__progress_01_4_01_4.html',1,'grpc_core::for_each_detail']]],
  ['nextvaluetraits_3c_20t_2c_20absl_3a_3avoid_5ft_3c_20typename_20t_3a_3avalue_5ftype_20_3e_20_3e_40',['NextValueTraits&lt; T, absl::void_t&lt; typename T::value_type &gt; &gt;',['../structgrpc__core_1_1for__each__detail_1_1_next_value_traits_3_01_t_00_01absl_1_1void__t_3_01type9524cfaf983000955c0af39a43be8bb6.html',1,'grpc_core::for_each_detail']]],
  ['nextvaluetraits_3c_20valueorfailure_3c_20std_3a_3aoptional_3c_20t_20_3e_20_3e_20_3e_41',['NextValueTraits&lt; ValueOrFailure&lt; std::optional&lt; T &gt; &gt; &gt;',['../structgrpc__core_1_1for__each__detail_1_1_next_value_traits_3_01_value_or_failure_3_01std_1_1optional_3_01_t_01_4_01_4_01_4.html',1,'grpc_core::for_each_detail']]],
  ['nextwrite_42',['NextWrite',['../structgrpc__core_1_1chaotic__good_1_1data__endpoints__detail_1_1_next_write.html',1,'grpc_core::chaotic_good::data_endpoints_detail']]],
  ['nginx_43',['Apache, PHP-FPM and Nginx',['..//Users/nikhil/Programming/GitHub/grpc/src/php/README.md#autotoc_md150',1,'']]],
  ['no_20c_20compile_44',['&lt;a name=&quot;nocompile&quot;&gt;&lt;/a&gt;Generate proto and gRPC C# sources from .proto files (no C# compile)',['../md_src_2csharp_2_b_u_i_l_d-_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md55',1,'']]],
  ['nocompile_20a_20generate_20proto_20and_20grpc_20c_20sources_20from_20proto_20files_20no_20c_20compile_45',['&lt;a name=&quot;nocompile&quot;&gt;&lt;/a&gt;Generate proto and gRPC C# sources from .proto files (no C# compile)',['../md_src_2csharp_2_b_u_i_l_d-_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md55',1,'']]],
  ['nocompressioncompressor_46',['NoCompressionCompressor',['../structgrpc__core_1_1_no_compression_compressor.html',1,'grpc_core']]],
  ['node_47',['Node',['../structgrpc__core_1_1_multi_producer_single_consumer_queue_1_1_node.html',1,'grpc_core::MultiProducerSingleConsumerQueue::Node'],['../classgrpc__core_1_1_xds_bootstrap_1_1_node.html',1,'grpc_core::XdsBootstrap::Node'],['../classtsi_1_1_ssl_session_l_r_u_cache_1_1_node.html',1,'tsi::SslSessionLRUCache::Node']]],
  ['nodegrpcgenerator_48',['NodeGrpcGenerator',['../class_node_grpc_generator.html',1,'']]],
  ['nodestruct_49',['NoDestruct',['../classgrpc__core_1_1_no_destruct.html',1,'grpc_core']]],
  ['nodestructsingleton_50',['NoDestructSingleton',['../classgrpc__core_1_1_no_destruct_singleton.html',1,'grpc_core']]],
  ['nointerceptor_51',['NoInterceptor',['../structgrpc__core_1_1_no_interceptor.html',1,'grpc_core']]],
  ['nonforwardingaction_52',['NonForwardingAction',['../structgrpc__core_1_1_xds_route_config_resource_1_1_route_1_1_non_forwarding_action.html',1,'grpc_core::XdsRouteConfigResource::Route']]],
  ['nonpolymorphicrefcount_53',['NonPolymorphicRefCount',['../classgrpc__core_1_1_non_polymorphic_ref_count.html',1,'grpc_core']]],
  ['noopcertificateverifier_54',['NoOpCertificateVerifier',['../classgrpc__core_1_1_no_op_certificate_verifier.html',1,'grpc_core']]],
  ['noopfetchbody_55',['NoOpFetchBody',['../classgrpc__core_1_1_external_account_credentials_1_1_no_op_fetch_body.html',1,'grpc_core::ExternalAccountCredentials']]],
  ['nosuchmethoderror_56',['NoSuchMethodError',['../classgrpc_1_1framework_1_1interfaces_1_1base_1_1base_1_1_no_such_method_error.html',1,'grpc.framework.interfaces.base.base.NoSuchMethodError'],['../classgrpc_1_1framework_1_1interfaces_1_1face_1_1face_1_1_no_such_method_error.html',1,'grpc.framework.interfaces.face.face.NoSuchMethodError']]],
  ['not_5freally_5fsecure_5fchannel_57',['not_really_secure_channel',['../namespacetests_1_1unit_1_1beta_1_1test__utilities.html#acff5950d6ecbda3edab67c3c52487abb',1,'tests::unit::beta::test_utilities']]],
  ['notauthorizationmatcher_58',['NotAuthorizationMatcher',['../classgrpc__core_1_1_not_authorization_matcher.html',1,'grpc_core']]],
  ['notes_59',['Notes',['../md_src_2objective-c_2_r_e_a_d_m_e-_c_f_s_t_r_e_a_m.html#autotoc_md102',1,'']]],
  ['notfoundtest_60',['NotFoundTest',['../classtests_1_1unit_1_1beta_1_1__not__found__test_1_1_not_found_test.html',1,'tests::unit::beta::_not_found_test']]],
  ['notification_61',['Notification',['../classgrpc__core_1_1_notification.html',1,'grpc_core']]],
  ['notifier_62',['Notifier',['../classgrpc__core_1_1_async_connectivity_state_watcher_interface_1_1_notifier.html',1,'grpc_core::AsyncConnectivityStateWatcherInterface']]],
  ['notifywrappedcalldealloc_3a_63',['notifyWrappedCallDealloc:',['../interface_g_r_p_c_pooled_channel.html#ab96aacca498889d48b23295af29b0443',1,'GRPCPooledChannel']]],
  ['notitle_64',['notitle',['../index.html',1,'']]],
  ['npcmetricskeyvalueiterable_65',['NPCMetricsKeyValueIterable',['../classgrpc_1_1internal_1_1_open_telemetry_plugin_impl_1_1_n_p_c_metrics_key_value_iterable.html',1,'grpc::internal::OpenTelemetryPluginImpl']]],
  ['nsdata_28grpc_29_66',['NSData(GRPC)',['../category_n_s_data_07_g_r_p_c_08.html',1,'']]],
  ['nsdata_28grpcmetadata_29_67',['NSData(GRPCMetadata)',['../category_n_s_data_07_g_r_p_c_metadata_08.html',1,'']]],
  ['nsdictionary_28grpc_29_68',['NSDictionary(GRPC)',['../category_n_s_dictionary_07_g_r_p_c_08.html',1,'']]],
  ['nsenumerator_28grxutil_29_69',['NSEnumerator(GRXUtil)',['../category_n_s_enumerator_07_g_r_x_util_08.html',1,'']]],
  ['nserror_28grpc_29_70',['NSError(GRPC)',['../category_n_s_error_07_g_r_p_c_08.html',1,'']]],
  ['nserrorunittests_71',['NSErrorUnitTests',['../interface_n_s_error_unit_tests.html',1,'']]],
  ['nsmutabledictionary_28grpcrequestheaders_29_72',['NSMutableDictionary(GRPCRequestHeaders)',['../category_n_s_mutable_dictionary_07_g_r_p_c_request_headers_08.html',1,'']]],
  ['nsstring_28grpcmetadata_29_73',['NSString(GRPCMetadata)',['../category_n_s_string_07_g_r_p_c_metadata_08.html',1,'']]],
  ['nuget_20a_20including_20tt_20proto_20tt_20files_20in_20nuget_20packages_74',['&lt;a name=&quot;proto-only-nuget&quot;&gt;&lt;/a&gt;Including &lt;tt&gt;.proto&lt;/tt&gt; files in NuGet packages',['../md_src_2csharp_2_b_u_i_l_d-_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md65',1,'']]],
  ['nuget_20package_75',['NuGet package',['../md_src_2csharp_2_b_u_i_l_d-_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md66',1,'Creating the NuGet package'],['../md_src_2csharp_2_grpc_8_tools_2implementation__notes.html#autotoc_md71',1,'Files in the NuGet package'],['../md_src_2csharp_2_b_u_i_l_d-_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md67',1,'Using the NuGet package']]],
  ['nuget_20packages_76',['&lt;a name=&quot;proto-only-nuget&quot;&gt;&lt;/a&gt;Including &lt;tt&gt;.proto&lt;/tt&gt; files in NuGet packages',['../md_src_2csharp_2_b_u_i_l_d-_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md65',1,'']]],
  ['null_77',['Null',['../structgrpc__core_1_1arena__promise__detail_1_1_null.html',1,'grpc_core::arena_promise_detail']]],
  ['num_78',['Num',['../class_math_1_1_num.html',1,'Math']]],
  ['num_5fincoming_5fstreams_5fbefore_5fsettings_5fack_79',['num_incoming_streams_before_settings_ack',['../structgrpc__chttp2__transport.html#a80563bd822d12dfeaea5db6dd033d791',1,'grpc_chttp2_transport']]],
  ['num_5fpending_5finduced_5fframes_80',['num_pending_induced_frames',['../structgrpc__chttp2__transport.html#a5f9222a35f2502067b57411bf9081113',1,'grpc_chttp2_transport']]]
];
