var searchData=
[
  ['package_0',['package',['..//Users/nikhil/Programming/GitHub/grpc/src/php/README.md#autotoc_md136',1,'Composer package'],['../md_src_2csharp_2_b_u_i_l_d-_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md66',1,'Creating the NuGet package'],['../md_src_2csharp_2_grpc_8_tools_2implementation__notes.html#autotoc_md71',1,'Files in the NuGet package'],['..//Users/nikhil/Programming/GitHub/grpc/src/cpp/README.md#autotoc_md29',1,'Install using vcpkg package'],['../md_src_2csharp_2_b_u_i_l_d-_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md67',1,'Using the NuGet package']]],
  ['packages_1',['&lt;a name=&quot;proto-only-nuget&quot;&gt;&lt;/a&gt;Including &lt;tt&gt;.proto&lt;/tt&gt; files in NuGet packages',['../md_src_2csharp_2_b_u_i_l_d-_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md65',1,'']]],
  ['packaging_20systems_2',['Packaging systems',['..//Users/nikhil/Programming/GitHub/grpc/src/cpp/README.md#autotoc_md28',1,'']]],
  ['padding_5f1_3',['padding_1',['../structgrpc__completion__queue.html#a540680d7b85aef6a1be70df1e79a9df6',1,'grpc_completion_queue']]],
  ['pages_4',['Visual Studio property pages',['../md_src_2csharp_2_grpc_8_tools_2implementation__notes.html#autotoc_md73',1,'']]],
  ['parameters_5',['Parameters',['../structgrpc__cpp__generator_1_1_parameters.html',1,'grpc_cpp_generator::Parameters'],['../structgrpc__node__generator_1_1_parameters.html',1,'grpc_node_generator::Parameters'],['../structgrpc__objective__c__generator_1_1_parameters.html',1,'grpc_objective_c_generator::Parameters']]],
  ['parent_5fhelper_6',['parent_helper',['../classgrpc__core_1_1_load_balancing_policy_1_1_parent_owning_delegating_channel_control_helper.html#aec2542665a68adb48ceb53f3dcbae712',1,'grpc_core::LoadBalancingPolicy::ParentOwningDelegatingChannelControlHelper']]],
  ['parentcall_7',['ParentCall',['../structgrpc__core_1_1_call_1_1_parent_call.html',1,'grpc_core::Call']]],
  ['parentowningdelegatingchannelcontrolhelper_8',['ParentOwningDelegatingChannelControlHelper',['../classgrpc__core_1_1_load_balancing_policy_1_1_parent_owning_delegating_channel_control_helper.html',1,'grpc_core::LoadBalancingPolicy']]],
  ['parentowningdelegatingchannelcontrolhelper_3c_20childpolicyhandler_20_3e_9',['ParentOwningDelegatingChannelControlHelper&lt; ChildPolicyHandler &gt;',['../classgrpc__core_1_1_load_balancing_policy_1_1_parent_owning_delegating_channel_control_helper.html',1,'grpc_core::LoadBalancingPolicy']]],
  ['parentscope_10',['ParentScope',['../structgrpc__core_1_1latent__see_1_1_parent_scope.html',1,'grpc_core::latent_see']]],
  ['parsedconfig_11',['ParsedConfig',['../classgrpc__core_1_1_service_config_parser_1_1_parsed_config.html',1,'grpc_core::ServiceConfigParser']]],
  ['parsedmetadata_12',['ParsedMetadata',['../classgrpc__core_1_1_parsed_metadata.html',1,'grpc_core']]],
  ['parsedmetadata_3c_20grpc_5fmetadata_5fbatch_20_3e_13',['ParsedMetadata&lt; grpc_metadata_batch &gt;',['../classgrpc__core_1_1_parsed_metadata.html',1,'grpc_core']]],
  ['parsedmethod_14',['ParsedMethod',['../structgrpc_1_1internal_1_1_gcp_observability_config_1_1_cloud_logging_1_1_rpc_event_configuration_1_1_parsed_method.html',1,'grpc::internal::GcpObservabilityConfig::CloudLogging::RpcEventConfiguration::ParsedMethod'],['../structgrpc_1_1internal_1_1_observability_logging_sink_1_1_configuration_1_1_parsed_method.html',1,'grpc::internal::ObservabilityLoggingSink::Configuration::ParsedMethod']]],
  ['parsehelper_15',['ParseHelper',['../classgrpc__core_1_1metadata__detail_1_1_parse_helper.html',1,'grpc_core::metadata_detail']]],
  ['parseloadbalancingconfig_16',['ParseLoadBalancingConfig',['../classgrpc__core_1_1_load_balancing_policy_registry.html#a2b911533b6ddc997424296869366fc95',1,'grpc_core::LoadBalancingPolicyRegistry']]],
  ['parser_17',['Parser',['../structgrpc__chttp2__transport_1_1_parser.html',1,'grpc_chttp2_transport::Parser'],['../classgrpc__core_1_1_h_pack_parser_1_1_parser.html',1,'grpc_core::HPackParser::Parser'],['../classgrpc__core_1_1_service_config_parser_1_1_parser.html',1,'grpc_core::ServiceConfigParser::Parser'],['../class_h_pack_parser_1_1_parser.html',1,'HPackParser::Parser']]],
  ['parsevalue_18',['ParseValue',['../structgrpc__core_1_1metadata__detail_1_1_parse_value.html',1,'grpc_core::metadata_detail']]],
  ['partial_19',['partial',['../structgrpc__chttp2__begin__write__result.html#ab80000586dcac5235ec6b5ebaf5e2cb6',1,'grpc_chttp2_begin_write_result']]],
  ['party_20',['Party',['../classgrpc__core_1_1_party.html',1,'grpc_core']]],
  ['passivelistenerimpl_21',['PassiveListenerImpl',['../classgrpc__core_1_1experimental_1_1_passive_listener_impl.html',1,'grpc_core::experimental']]],
  ['passthroughobserver_22',['PassthroughObserver',['../interface_passthrough_observer.html',1,'']]],
  ['patch_20for_20grpc_20python_23',['Writing Your First Patch for gRPC Python',['../md_src_2python_2_c_o_n_t_r_i_b_u_t_i_n_g.html#autotoc_md163',1,'']]],
  ['patchedprotobuf_24',['PatchedProtobuf',['../class_grpc_1_1_tools_1_1_proto_compiler_outputs.html#a4ad464822dd1de462c438c591303e712',1,'Grpc::Tools::ProtoCompilerOutputs']]],
  ['path_25',['path',['../structgrpc__core_1_1_load_balancing_policy_1_1_pick_args.html#a1d3d2fb585948ba37c1cab1180379eea',1,'grpc_core::LoadBalancingPolicy::PickArgs::path'],['../interface_g_r_p_c_request_options.html#a80855bd704d0e4f82894f99ce25562ed',1,'GRPCRequestOptions::path']]],
  ['pathauthorizationmatcher_26',['PathAuthorizationMatcher',['../classgrpc__core_1_1_path_authorization_matcher.html',1,'grpc_core']]],
  ['pause_27',['pause',['../classtests_1_1unit_1_1framework_1_1common_1_1test__control_1_1_pause_fail_control.html#a9a9d319fd296993a4c2bc406d21e6f59',1,'tests::unit::framework::common::test_control::PauseFailControl']]],
  ['pausefailcontrol_28',['PauseFailControl',['../classtests_1_1unit_1_1framework_1_1common_1_1test__control_1_1_pause_fail_control.html',1,'tests::unit::framework::common::test_control']]],
  ['payload_29',['Payload',['../structgrpc_1_1internal_1_1_logging_sink_1_1_entry_1_1_payload.html',1,'grpc::internal::LoggingSink::Entry::Payload'],['../class_grpc_1_1_testing_1_1_payload.html',1,'Grpc\Testing\Payload'],['../structgrpc__core_1_1_logging_sink_1_1_entry_1_1_payload.html',1,'grpc_core::LoggingSink::Entry::Payload']]],
  ['payload_30',['payload',['../structgrpc__transport__stream__op__batch.html#a437c131b735b414589594f867b1869e1',1,'grpc_transport_stream_op_batch']]],
  ['payloadchunker_31',['PayloadChunker',['../classgrpc__core_1_1chaotic__good_1_1message__chunker__detail_1_1_payload_chunker.html',1,'grpc_core::chaotic_good::message_chunker_detail::PayloadChunker'],['../classgrpc__core_1_1chaotic__good__legacy_1_1message__chunker__detail_1_1_payload_chunker.html',1,'grpc_core::chaotic_good_legacy::message_chunker_detail::PayloadChunker']]],
  ['payloadconfig_32',['PayloadConfig',['../class_grpc_1_1_testing_1_1_payload_config.html',1,'Grpc::Testing']]],
  ['payloads_33',['Payloads',['../class_g_p_b_metadata_1_1_src_1_1_proto_1_1_grpc_1_1_testing_1_1_payloads.html',1,'GPBMetadata::Src::Proto::Grpc::Testing']]],
  ['payloadtype_34',['PayloadType',['../class_grpc_1_1_testing_1_1_payload_type.html',1,'Grpc::Testing']]],
  ['pbempty_35',['PBEmpty',['../class_g_p_b_metadata_1_1_src_1_1_proto_1_1_grpc_1_1_testing_1_1_p_b_empty.html',1,'GPBMetadata::Src::Proto::Grpc::Testing']]],
  ['pbreturn_36',['PBRETURN',['../class_grpc_1_1_testing_1_1_hook_request_1_1_hook_request_command.html#a7fa9b1081d2b949c10c3b1249bcab09e',1,'Grpc::Testing::HookRequest::HookRequestCommand']]],
  ['pbvoid_37',['PBVoid',['../class_grpc_1_1_testing_1_1_p_b_void.html',1,'Grpc::Testing']]],
  ['pcntl_5ffork_20support_38',['pcntl_fork() support',['..//Users/nikhil/Programming/GitHub/grpc/src/php/README.md#autotoc_md153',1,'']]],
  ['pecl_39',['Install from PECL',['..//Users/nikhil/Programming/GitHub/grpc/src/php/README.md#autotoc_md130',1,'']]],
  ['peer_40',['peer',['../classgrpc_1_1_servicer_context.html#a546bc944e052f9282f67bd8e92ef922b',1,'grpc.ServicerContext.peer()'],['../classgrpc_1_1__server_1_1___context.html#aaa31f39f8b48b1a06d12b89a46eb9ae7',1,'grpc._server._Context.peer()'],['../classgrpc_1_1aio_1_1__base__server_1_1_servicer_context.html#ad2075e33d7bc158f07cf06f6c7b1f12a',1,'grpc.aio._base_server.ServicerContext.peer()'],['../classgrpc_1_1beta_1_1__server__adaptations_1_1___server_protocol_context.html#a001413023f0ea5b1641cd118c8afffa1',1,'grpc.beta._server_adaptations._ServerProtocolContext.peer()'],['../classgrpc_1_1beta_1_1interfaces_1_1_g_r_p_c_servicer_context.html#a2996f39af0a9f1f4376f90cb27099266',1,'grpc.beta.interfaces.GRPCServicerContext.peer()'],['../classgrpc__testing_1_1__server_1_1__servicer__context_1_1_servicer_context.html#a915c8857282cf12154e8fb50f52a3deb',1,'grpc_testing._server._servicer_context.ServicerContext.peer()']]],
  ['peer_5fidentities_41',['peer_identities',['../classgrpc_1_1_servicer_context.html#abd4c0165910265a81fd884cef14df2a2',1,'grpc.ServicerContext.peer_identities()'],['../classgrpc_1_1__server_1_1___context.html#a9918081ef4ea54b0dfe0a0eda6e986fa',1,'grpc._server._Context.peer_identities()'],['../classgrpc_1_1aio_1_1__base__server_1_1_servicer_context.html#a2e1cd00ba04df3da0dc0a5d03dfe5855',1,'grpc.aio._base_server.ServicerContext.peer_identities()'],['../classgrpc__testing_1_1__server_1_1__servicer__context_1_1_servicer_context.html#a964a237d06a89917c1b988ee8af8bb4b',1,'grpc_testing._server._servicer_context.ServicerContext.peer_identities()']]],
  ['peer_5fidentity_5fkey_42',['peer_identity_key',['../classgrpc_1_1_servicer_context.html#a6f77554f90497ac9b3a285c1c74f6213',1,'grpc.ServicerContext.peer_identity_key()'],['../classgrpc_1_1__server_1_1___context.html#acc0a0e9dc302195e30148c2d5585f710',1,'grpc._server._Context.peer_identity_key()'],['../classgrpc_1_1aio_1_1__base__server_1_1_servicer_context.html#af3961bbcd1abed8c93769ffc0c3ad828',1,'grpc.aio._base_server.ServicerContext.peer_identity_key()'],['../classgrpc__testing_1_1__server_1_1__servicer__context_1_1_servicer_context.html#a6d9e0f1238217157bd42deabb7d493d3',1,'grpc_testing._server._servicer_context.ServicerContext.peer_identity_key()']]],
  ['peerstring_43',['PeerString',['../structgrpc__core_1_1_peer_string.html',1,'grpc_core']]],
  ['pemcertificatechain_44',['PEMCertificateChain',['../interface_g_r_p_c_call_options.html#a366ef2da494a1775ad8086b66f88f46e',1,'GRPCCallOptions::PEMCertificateChain'],['../interface_g_r_p_c_mutable_call_options.html#a0395f7963b3aafcd23134aa45b0cb540',1,'GRPCMutableCallOptions::PEMCertificateChain']]],
  ['pemkeycertpair_45',['PemKeyCertPair',['../classgrpc__core_1_1_pem_key_cert_pair.html',1,'grpc_core']]],
  ['pemprivatekey_46',['PEMPrivateKey',['../interface_g_r_p_c_call_options.html#ae62a83a8eaee16969d3b6a260f0232f6',1,'GRPCCallOptions::PEMPrivateKey'],['../interface_g_r_p_c_mutable_call_options.html#ae2acdf2fe250cebdbd4ddc2aae84c4f5',1,'GRPCMutableCallOptions::PEMPrivateKey']]],
  ['pemrootcertificates_47',['PEMRootCertificates',['../interface_g_r_p_c_call_options.html#a76406ede45d7edc906ea5c6b2456825f',1,'GRPCCallOptions::PEMRootCertificates'],['../interface_g_r_p_c_mutable_call_options.html#aede2e87ee80a80244d52477cc660f039',1,'GRPCMutableCallOptions::PEMRootCertificates'],['../interface_test_base.html#a40db2851de8e6db68f5faeb90ffb2f33',1,'TestBase::PEMRootCertificates()']]],
  ['pending_48',['Pending',['../structgrpc__core_1_1_pending.html',1,'grpc_core']]],
  ['pendingconnection_49',['PendingConnection',['../classgrpc__core_1_1chaotic__good_1_1_pending_connection.html',1,'grpc_core::chaotic_good::PendingConnection'],['../classgrpc__core_1_1chaotic__good__legacy_1_1_pending_connection.html',1,'grpc_core::chaotic_good_legacy::PendingConnection']]],
  ['per_20file_20tt_20proto_20tt_20file_20options_50',['&lt;a name=&quot;visualstudio&quot;&gt;&lt;/a&gt;Visual Studio: setting per-file &lt;tt&gt;.proto&lt;/tt&gt; file options',['../md_src_2csharp_2_b_u_i_l_d-_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md57',1,'']]],
  ['perbalancerstore_51',['PerBalancerStore',['../classgrpc_1_1load__reporter_1_1_per_balancer_store.html',1,'grpc::load_reporter']]],
  ['perchannelargs_52',['PerChannelArgs',['../structgrpc__core_1_1_evaluate_args_1_1_per_channel_args.html',1,'grpc_core::EvaluateArgs']]],
  ['percpu_53',['PerCpu',['../classgrpc__core_1_1_per_cpu.html',1,'grpc_core']]],
  ['percpu_3c_20data_20_3e_54',['PerCpu&lt; Data &gt;',['../classgrpc__core_1_1_per_cpu.html',1,'grpc_core']]],
  ['percpu_3c_20fragment_20_3e_55',['PerCpu&lt; Fragment &gt;',['../classgrpc__core_1_1_per_cpu.html',1,'grpc_core']]],
  ['percpu_3c_20percpudata_20_3e_56',['PerCpu&lt; PerCpuData &gt;',['../classgrpc__core_1_1_per_cpu.html',1,'grpc_core']]],
  ['percpu_3c_20stats_20_3e_57',['PerCpu&lt; Stats &gt;',['../classgrpc__core_1_1_per_cpu.html',1,'grpc_core']]],
  ['percpucallcountinghelper_58',['PerCpuCallCountingHelper',['../classgrpc__core_1_1channelz_1_1_per_cpu_call_counting_helper.html',1,'grpc_core::channelz']]],
  ['percpuoptions_59',['PerCpuOptions',['../classgrpc__core_1_1_per_cpu_options.html',1,'grpc_core']]],
  ['percpushardinghelper_60',['PerCpuShardingHelper',['../classgrpc__core_1_1_per_cpu_sharding_helper.html',1,'grpc_core']]],
  ['performance_61',['C implementation (for better performance)',['..//Users/nikhil/Programming/GitHub/grpc/src/php/README.md#autotoc_md141',1,'']]],
  ['perftests_62',['PerfTests',['../interface_perf_tests.html',1,'']]],
  ['perftestsblockcallbacks_63',['PerfTestsBlockCallbacks',['../interface_perf_tests_block_callbacks.html',1,'']]],
  ['perftestscfstreamcleartext_64',['PerfTestsCFStreamCleartext',['../interface_perf_tests_c_f_stream_cleartext.html',1,'']]],
  ['perftestscfstreamssl_65',['PerfTestsCFStreamSSL',['../interface_perf_tests_c_f_stream_s_s_l.html',1,'']]],
  ['perftestsnocfstreamcleartext_66',['PerfTestsNoCFStreamCleartext',['../interface_perf_tests_no_c_f_stream_cleartext.html',1,'']]],
  ['perftestsnocfstreamssl_67',['PerfTestsNoCFStreamSSL',['../interface_perf_tests_no_c_f_stream_s_s_l.html',1,'']]],
  ['perhoststore_68',['PerHostStore',['../classgrpc_1_1load__reporter_1_1_per_host_store.html',1,'grpc::load_reporter']]],
  ['periodicupdate_69',['PeriodicUpdate',['../classgrpc__core_1_1_periodic_update.html',1,'grpc_core']]],
  ['permission_70',['Permission',['../structgrpc__core_1_1_rbac_1_1_permission.html',1,'grpc_core::Rbac']]],
  ['persistentchanneltest_71',['PersistentChannelTest',['../class_persistent_channel_test.html',1,'']]],
  ['phonyinterceptor_72',['PhonyInterceptor',['../interface_phony_interceptor.html',1,'']]],
  ['phonyinterceptorfactory_73',['PhonyInterceptorFactory',['../interface_phony_interceptor_factory.html',1,'']]],
  ['phonyinvalidclient_74',['PhonyInvalidClient',['../class_phony_invalid_client.html',1,'']]],
  ['php_20classes_20from_20your_20service_20definition_75',['Generate PHP classes from your service definition',['..//Users/nikhil/Programming/GitHub/grpc/src/php/README.md#autotoc_md143',1,'']]],
  ['php_20fpm_20and_20nginx_76',['Apache, PHP-FPM and Nginx',['..//Users/nikhil/Programming/GitHub/grpc/src/php/README.md#autotoc_md150',1,'']]],
  ['php_20future_20tt_77',['&lt;tt&gt;php-future&lt;/tt&gt;',['..//Users/nikhil/Programming/GitHub/grpc/src/php/docker/README.md#autotoc_md123',1,'']]],
  ['php_20implementation_20for_20easier_20installation_78',['PHP implementation (for easier installation)',['..//Users/nikhil/Programming/GitHub/grpc/src/php/README.md#autotoc_md142',1,'']]],
  ['php_20ini_79',['Update php.ini',['..//Users/nikhil/Programming/GitHub/grpc/src/php/README.md#autotoc_md135',1,'']]],
  ['php_20src_20tt_80',['&lt;tt&gt;php-src&lt;/tt&gt;',['..//Users/nikhil/Programming/GitHub/grpc/src/php/docker/README.md#autotoc_md121',1,'']]],
  ['php_20zts_20tt_81',['&lt;tt&gt;php-zts&lt;/tt&gt;',['..//Users/nikhil/Programming/GitHub/grpc/src/php/docker/README.md#autotoc_md122',1,'']]],
  ['php5_20tt_82',['&lt;tt&gt;php5&lt;/tt&gt;',['..//Users/nikhil/Programming/GitHub/grpc/src/php/docker/README.md#autotoc_md124',1,'']]],
  ['phpgrpcgenerator_83',['PHPGrpcGenerator',['../class_p_h_p_grpc_generator.html',1,'']]],
  ['pickargs_84',['PickArgs',['../structgrpc__core_1_1_load_balancing_policy_1_1_pick_args.html',1,'grpc_core::LoadBalancingPolicy']]],
  ['pickresult_85',['PickResult',['../structgrpc__core_1_1_load_balancing_policy_1_1_pick_result.html',1,'grpc_core::LoadBalancingPolicy']]],
  ['ping_5fabuse_5fpolicy_86',['ping_abuse_policy',['../structgrpc__chttp2__transport.html#a107f10b24591bf7d88b46934c0c6dffd',1,'grpc_chttp2_transport']]],
  ['ping_5fack_5fcount_87',['ping_ack_count',['../structgrpc__chttp2__transport.html#a4548fb783cce684e57e56ac7ad75f520',1,'grpc_chttp2_transport']]],
  ['ping_5ftimeout_88',['ping_timeout',['../structgrpc__chttp2__transport.html#ad335e21d69d6efc178450f47871623fe',1,'grpc_chttp2_transport']]],
  ['pinginterface_89',['PingInterface',['../classgrpc__core_1_1http2_1_1_ping_interface.html',1,'grpc_core::http2']]],
  ['pingmanager_90',['PingManager',['../classgrpc__core_1_1http2_1_1_ping_manager.html',1,'grpc_core::http2']]],
  ['pipe_91',['Pipe',['../structgrpc__core_1_1_pipe.html',1,'grpc_core']]],
  ['pipe_92',['pipe',['../interface_g_r_x_buffered_pipe.html#aa177dbdaf3f1082f76575ffd5b97716f',1,'GRXBufferedPipe']]],
  ['pipe_3c_20messagehandle_20_3e_93',['Pipe&lt; MessageHandle &gt;',['../structgrpc__core_1_1_pipe.html',1,'grpc_core']]],
  ['pipe_3c_20servermetadatahandle_20_3e_94',['Pipe&lt; ServerMetadataHandle &gt;',['../structgrpc__core_1_1_pipe.html',1,'grpc_core']]],
  ['pipemapper_95',['PipeMapper',['../classgrpc__core_1_1_pipe_mapper.html',1,'grpc_core']]],
  ['pipereceiver_96',['PipeReceiver',['../classgrpc__core_1_1_pipe_receiver.html',1,'grpc_core']]],
  ['pipereceiver_3c_20messagehandle_20_3e_97',['PipeReceiver&lt; MessageHandle &gt;',['../classgrpc__core_1_1_pipe_receiver.html',1,'grpc_core']]],
  ['pipereceiver_3c_20servermetadatahandle_20_3e_98',['PipeReceiver&lt; ServerMetadataHandle &gt;',['../classgrpc__core_1_1_pipe_receiver.html',1,'grpc_core']]],
  ['pipesender_99',['PipeSender',['../classgrpc__core_1_1_pipe_sender.html',1,'grpc_core']]],
  ['pipesender_3c_20messagehandle_20_3e_100',['PipeSender&lt; MessageHandle &gt;',['../classgrpc__core_1_1_pipe_sender.html',1,'grpc_core']]],
  ['pipesender_3c_20servermetadatahandle_20_3e_101',['PipeSender&lt; ServerMetadataHandle &gt;',['../classgrpc__core_1_1_pipe_sender.html',1,'grpc_core']]],
  ['pipewakeupfd_102',['PipeWakeupFd',['../classgrpc__event__engine_1_1experimental_1_1_pipe_wakeup_fd.html',1,'grpc_event_engine::experimental']]],
  ['pkg_20config_103',['pkg-config',['..//Users/nikhil/Programming/GitHub/grpc/src/cpp/README.md#autotoc_md26',1,'']]],
  ['platforms_104',['Supported Platforms',['..//Users/nikhil/Programming/GitHub/grpc/src/cpp/README.md#autotoc_md19',1,'']]],
  ['plugin_105',['plugin',['..//Users/nikhil/Programming/GitHub/grpc/src/php/README.md#autotoc_md139',1,'&lt;tt&gt;grpc_php_plugin&lt;/tt&gt; protoc plugin'],['..//Users/nikhil/Programming/GitHub/grpc/src/objective-c/README.md#autotoc_md109',1,'Install &lt;em&gt;protoc&lt;/em&gt; with the gRPC plugin']]],
  ['plugin_20binaries_106',['Protobuf compiler and C# gRPC plugin binaries',['../md_src_2csharp_2_grpc_8_tools_2implementation__notes.html#autotoc_md75',1,'']]],
  ['plugin_20without_20using_20homebrew_107',['Install &lt;em&gt;protoc&lt;/em&gt; and the gRPC plugin without using Homebrew',['..//Users/nikhil/Programming/GitHub/grpc/src/objective-c/README.md#autotoc_md110',1,'']]],
  ['plugin_5fstate_108',['plugin_state',['../structplugin__state.html',1,'']]],
  ['plugindefinition_109',['PluginDefinition',['../structgrpc__core_1_1_certificate_provider_store_1_1_plugin_definition.html',1,'grpc_core::CertificateProviderStore']]],
  ['pointer_110',['Pointer',['../classgrpc__core_1_1_channel_args_1_1_pointer.html',1,'grpc_core::ChannelArgs']]],
  ['poissonparams_111',['PoissonParams',['../class_grpc_1_1_testing_1_1_poisson_params.html',1,'Grpc::Testing']]],
  ['policy_112',['Policy',['../structgrpc__core_1_1_rbac_1_1_policy.html',1,'grpc_core::Rbac']]],
  ['policyauthorizationmatcher_113',['PolicyAuthorizationMatcher',['../classgrpc__core_1_1_policy_authorization_matcher.html',1,'grpc_core']]],
  ['poll_114',['Poll',['../classgrpc__core_1_1_poll.html',1,'grpc_core']]],
  ['poll_3c_20empty_20_3e_115',['Poll&lt; Empty &gt;',['../classgrpc__core_1_1_poll_3_01_empty_01_4.html',1,'grpc_core']]],
  ['poll_3c_20grpc_5fcore_3a_3afilters_5fdetail_3a_3aresultor_3c_20input_20_3e_20_3e_116',['Poll&lt; grpc_core::filters_detail::ResultOr&lt; Input &gt; &gt;',['../classgrpc__core_1_1_poll.html',1,'grpc_core']]],
  ['poll_3c_20grpc_5fcore_3a_3afilters_5fdetail_3a_3aresultor_3c_20messagehandle_20_3e_20_3e_117',['Poll&lt; grpc_core::filters_detail::ResultOr&lt; MessageHandle &gt; &gt;',['../classgrpc__core_1_1_poll.html',1,'grpc_core']]],
  ['poll_3c_20grpc_5fcore_3a_3afilters_5fdetail_3a_3aresultor_3c_20t_20_3e_20_3e_118',['Poll&lt; grpc_core::filters_detail::ResultOr&lt; T &gt; &gt;',['../classgrpc__core_1_1_poll.html',1,'grpc_core']]],
  ['poll_3c_20result_20_3e_119',['Poll&lt; Result &gt;',['../classgrpc__core_1_1_poll.html',1,'grpc_core']]],
  ['poll_3c_20servermetadatahandle_20_3e_120',['Poll&lt; ServerMetadataHandle &gt;',['../classgrpc__core_1_1_poll.html',1,'grpc_core']]],
  ['pollbatchlogger_121',['PollBatchLogger',['../classgrpc__core_1_1_poll_batch_logger.html',1,'grpc_core']]],
  ['pollcastimpl_122',['PollCastImpl',['../structgrpc__core_1_1_poll_cast_impl.html',1,'grpc_core']]],
  ['pollcastimpl_3c_20t_2c_20poll_3c_20t_20_3e_20_3e_123',['PollCastImpl&lt; T, Poll&lt; T &gt; &gt;',['../structgrpc__core_1_1_poll_cast_impl_3_01_t_00_01_poll_3_01_t_01_4_01_4.html',1,'grpc_core']]],
  ['pollcastimpl_3c_20t_2c_20poll_3c_20u_20_3e_20_3e_124',['PollCastImpl&lt; T, Poll&lt; U &gt; &gt;',['../structgrpc__core_1_1_poll_cast_impl_3_01_t_00_01_poll_3_01_u_01_4_01_4.html',1,'grpc_core']]],
  ['pollcastimpl_3c_20t_2c_20t_20_3e_125',['PollCastImpl&lt; T, T &gt;',['../structgrpc__core_1_1_poll_cast_impl_3_01_t_00_01_t_01_4.html',1,'grpc_core']]],
  ['pollcastimpl_3c_20t_2c_20u_2c_20std_3a_3aenable_5fif_3c_21polltraits_3c_20u_20_3e_3a_3ais_5fpoll_28_29_3e_20_3e_126',['PollCastImpl&lt; T, U, std::enable_if&lt;!PollTraits&lt; U &gt;::is_poll()&gt; &gt;',['../structgrpc__core_1_1_poll_cast_impl_3_01_t_00_01_u_00_01std_1_1enable__if_3_9_poll_traits_3_01_u_01_4_1_1is__poll_07_08_4_01_4.html',1,'grpc_core']]],
  ['pollcontext_127',['PollContext',['../classgrpc__core_1_1promise__filter__detail_1_1_client_call_data_1_1_poll_context.html',1,'grpc_core::promise_filter_detail::ClientCallData::PollContext'],['../classgrpc__core_1_1promise__filter__detail_1_1_server_call_data_1_1_poll_context.html',1,'grpc_core::promise_filter_detail::ServerCallData::PollContext']]],
  ['poller_128',['Poller',['../classgrpc__event__engine_1_1experimental_1_1_poller.html',1,'grpc_event_engine::experimental']]],
  ['pollingresolver_129',['PollingResolver',['../classgrpc__core_1_1_polling_resolver.html',1,'grpc_core']]],
  ['pollpoller_130',['PollPoller',['../classgrpc__event__engine_1_1experimental_1_1_poll_poller.html',1,'grpc_event_engine::experimental']]],
  ['pollset_5fset_131',['pollset_set',['../structgrpc__core_1_1_resolver_args.html#a7c274d0eae06b5f2d380b362a914cda7',1,'grpc_core::ResolverArgs']]],
  ['polltraits_132',['PollTraits',['../structgrpc__core_1_1_poll_traits.html',1,'grpc_core']]],
  ['polltraits_3c_20decltype_28std_3a_3adeclval_3c_20readernext_20_3e_28_29_28_29_29_3e_133',['PollTraits&lt; decltype(std::declval&lt; ReaderNext &gt;()())&gt;',['../structgrpc__core_1_1_poll_traits.html',1,'grpc_core']]],
  ['polltraits_3c_20poll_3c_20t_20_3e_20_3e_134',['PollTraits&lt; Poll&lt; T &gt; &gt;',['../structgrpc__core_1_1_poll_traits_3_01_poll_3_01_t_01_4_01_4.html',1,'grpc_core']]],
  ['pollvisitor_135',['PollVisitor',['../classgrpc__core_1_1promise__detail_1_1_poll_visitor.html',1,'grpc_core::promise_detail']]],
  ['pollwrapper_136',['PollWrapper',['../structgrpc__core_1_1promise__detail_1_1_poll_wrapper.html',1,'grpc_core::promise_detail']]],
  ['pollwrapper_3c_20poll_3c_20t_20_3e_20_3e_137',['PollWrapper&lt; Poll&lt; T &gt; &gt;',['../structgrpc__core_1_1promise__detail_1_1_poll_wrapper_3_01_poll_3_01_t_01_4_01_4.html',1,'grpc_core::promise_detail']]],
  ['polymorphicrefcount_138',['PolymorphicRefCount',['../classgrpc__core_1_1_polymorphic_ref_count.html',1,'grpc_core']]],
  ['pool_139',['pool',['../namespacegrpc_1_1framework_1_1foundation_1_1logging__pool.html#afcb8de933d2e8d54d602b3673f6acfbb',1,'grpc::framework::foundation::logging_pool']]],
  ['pooleddeleter_140',['PooledDeleter',['../classgrpc__core_1_1_arena_1_1_pooled_deleter.html',1,'grpc_core::Arena']]],
  ['portauthorizationmatcher_141',['PortAuthorizationMatcher',['../classgrpc__core_1_1_port_authorization_matcher.html',1,'grpc_core']]],
  ['posixacceptcallback_142',['PosixAcceptCallback',['../classgrpc__event__engine_1_1experimental_1_1_event_engine_supports_fd_extension.html#a663485a5afb9204f626176f82f074a6a',1,'grpc_event_engine::experimental::EventEngineSupportsFdExtension::PosixAcceptCallback'],['../classgrpc__core_1_1_event_engine_supports_fd_extension.html#a663485a5afb9204f626176f82f074a6a',1,'grpc_core::EventEngineSupportsFdExtension::PosixAcceptCallback']]],
  ['posixdnsresolver_143',['PosixDNSResolver',['../classgrpc__event__engine_1_1experimental_1_1_posix_event_engine_1_1_posix_d_n_s_resolver.html',1,'grpc_event_engine::experimental::PosixEventEngine']]],
  ['posixendpoint_144',['PosixEndpoint',['../classgrpc__event__engine_1_1experimental_1_1_posix_endpoint.html',1,'grpc_event_engine::experimental']]],
  ['posixendpointwithchaoticgoodsupport_145',['PosixEndpointWithChaoticGoodSupport',['../classgrpc__event__engine_1_1experimental_1_1_posix_endpoint_with_chaotic_good_support.html',1,'grpc_event_engine::experimental']]],
  ['posixendpointwithfdsupport_146',['PosixEndpointWithFdSupport',['../classgrpc__event__engine_1_1experimental_1_1_posix_endpoint_with_fd_support.html',1,'grpc_event_engine::experimental']]],
  ['posixengineclosure_147',['PosixEngineClosure',['../classgrpc__event__engine_1_1experimental_1_1_posix_engine_closure.html',1,'grpc_event_engine::experimental']]],
  ['posixenginelistener_148',['PosixEngineListener',['../classgrpc__event__engine_1_1experimental_1_1_posix_engine_listener.html',1,'grpc_event_engine::experimental']]],
  ['posixeventengine_149',['PosixEventEngine',['../classgrpc__event__engine_1_1experimental_1_1_posix_event_engine.html',1,'grpc_event_engine::experimental']]],
  ['posixeventenginewithfdsupport_150',['PosixEventEngineWithFdSupport',['../classgrpc__event__engine_1_1experimental_1_1_posix_event_engine_with_fd_support.html',1,'grpc_event_engine::experimental']]],
  ['posixeventpoller_151',['PosixEventPoller',['../classgrpc__event__engine_1_1experimental_1_1_posix_event_poller.html',1,'grpc_event_engine::experimental']]],
  ['posixlistenerwithfdsupport_152',['PosixListenerWithFdSupport',['../classgrpc__event__engine_1_1experimental_1_1_posix_listener_with_fd_support.html',1,'grpc_event_engine::experimental']]],
  ['posixsocketcreateresult_153',['PosixSocketCreateResult',['../structgrpc__event__engine_1_1experimental_1_1_posix_socket_wrapper_1_1_posix_socket_create_result.html',1,'grpc_event_engine::experimental::PosixSocketWrapper']]],
  ['posixsocketwrapper_154',['PosixSocketWrapper',['../classgrpc__event__engine_1_1experimental_1_1_posix_socket_wrapper.html',1,'grpc_event_engine::experimental']]],
  ['posixtcpoptions_155',['PosixTcpOptions',['../structgrpc__core_1_1_posix_tcp_options.html',1,'grpc_core::PosixTcpOptions'],['../structgrpc__event__engine_1_1experimental_1_1_posix_tcp_options.html',1,'grpc_event_engine::experimental::PosixTcpOptions']]],
  ['possibleoutputs_156',['PossibleOutputs',['../class_grpc_1_1_tools_1_1_proto_compiler_outputs.html#a07e757b39f112abe82f8291eaab28788',1,'Grpc::Tools::ProtoCompilerOutputs']]],
  ['prepare_20the_20list_20of_20proto_20files_20to_20compile_157',['Prepare the list of .proto files to compile',['../md_src_2csharp_2_grpc_8_tools_2implementation__notes.html#autotoc_md80',1,'']]],
  ['prepend_158',['Prepend',['../classgrpc__core_1_1_slice_buffer.html#ab1452be9a74fac49c7332aa9cb470168',1,'grpc_core::SliceBuffer']]],
  ['preprocess_159',['Preprocess',['../classchannelz__commands_1_1_preprocess.html',1,'channelz_commands.Preprocess'],['../classhealth__commands_1_1_preprocess.html',1,'health_commands.Preprocess'],['../classreflection__commands_1_1_preprocess.html',1,'reflection_commands.Preprocess'],['../classstatus__commands_1_1_preprocess.html',1,'status_commands.Preprocess'],['../classtesting__commands_1_1_preprocess.html',1,'testing_commands.Preprocess']]],
  ['prerequisites_160',['PREREQUISITES',['..//Users/nikhil/Programming/GitHub/grpc/src/android/test/interop/README.md#autotoc_md0',1,'PREREQUISITES'],['..//Users/nikhil/Programming/GitHub/grpc/src/ruby/pb/README.md#autotoc_md175',1,'PREREQUISITES'],['..//Users/nikhil/Programming/GitHub/grpc/src/ruby/README.md#autotoc_md179',1,'PREREQUISITES']]],
  ['prerequisites_161',['Prerequisites',['..//Users/nikhil/Programming/GitHub/grpc/src/php/README.md#autotoc_md128',1,'Prerequisites'],['../md_src_2python_2_c_o_n_t_r_i_b_u_t_i_n_g.html#autotoc_md164',1,'Prerequisites']]],
  ['pressurecontroller_162',['PressureController',['../classgrpc__core_1_1memory__quota__detail_1_1_pressure_controller.html',1,'grpc_core::memory_quota_detail']]],
  ['pressureinfo_163',['PressureInfo',['../structgrpc__core_1_1_basic_memory_quota_1_1_pressure_info.html',1,'grpc_core::BasicMemoryQuota']]],
  ['pressuretracker_164',['PressureTracker',['../classgrpc__core_1_1memory__quota__detail_1_1_pressure_tracker.html',1,'grpc_core::memory_quota_detail']]],
  ['previoustimeout_165',['PreviousTimeout',['../structgrpc__core_1_1hpack__encoder__detail_1_1_previous_timeout.html',1,'grpc_core::hpack_encoder_detail']]],
  ['principal_166',['Principal',['../structgrpc__core_1_1_rbac_1_1_principal.html',1,'grpc_core::Rbac']]],
  ['printer_167',['Printer',['../structgrpc__generator_1_1_printer.html',1,'grpc_generator']]],
  ['prioritizedrace_168',['PrioritizedRace',['../classgrpc__core_1_1_prioritized_race.html',1,'grpc_core']]],
  ['prioritizedrace_3c_20promise_20_3e_169',['PrioritizedRace&lt; Promise &gt;',['../classgrpc__core_1_1_prioritized_race_3_01_promise_01_4.html',1,'grpc_core']]],
  ['prioritizedrace_3c_20promise_2c_20promises_2e_2e_2e_20_3e_170',['PrioritizedRace&lt; Promise, Promises... &gt;',['../classgrpc__core_1_1_prioritized_race_3_01_promise_00_01_promises_8_8_8_01_4.html',1,'grpc_core']]],
  ['priority_171',['Priority',['../structgrpc__core_1_1_xds_endpoint_resource_1_1_priority.html',1,'grpc_core::XdsEndpointResource']]],
  ['probabilitysampler_172',['ProbabilitySampler',['../classgrpc__observability_1_1_probability_sampler.html',1,'grpc_observability']]],
  ['program_173',['Program',['../class_test_app_1_1_program.html',1,'TestApp']]],
  ['project_174',['project',['../md_src_2csharp_2_b_u_i_l_d-_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md34',1,'Adding &lt;tt&gt;.proto&lt;/tt&gt; files to a project'],['..//Users/nikhil/Programming/GitHub/grpc/src/objective-c/README.md#autotoc_md105',1,'Integrate a proto library in your project']]],
  ['project_20build_175',['Hooking the custom targets into the project build',['../md_src_2csharp_2_grpc_8_tools_2implementation__notes.html#autotoc_md77',1,'']]],
  ['projectfolder_20protos_20tt_20and_20tt_20outsideprojectprotos_20tt_176',['&lt;tt&gt;ProjectFolder\\Protos&lt;/tt&gt; and &lt;tt&gt;..\\OutsideProjectProtos&lt;/tt&gt;',['../md_src_2csharp_2_b_u_i_l_d-_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md47',1,'']]],
  ['projects_177',['projects',['../md_src_2csharp_2_b_u_i_l_d-_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md59',1,'&quot;classic&quot; projects'],['../md_src_2csharp_2_b_u_i_l_d-_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md58',1,'&quot;dotnet SDK&quot; projects']]],
  ['projects_20in_20the_20same_20vs_20solution_178',['Sharing &lt;tt&gt;.proto&lt;/tt&gt; files between multiple projects (in the same VS solution)',['../md_src_2csharp_2_b_u_i_l_d-_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md35',1,'']]],
  ['promiseactivity_179',['PromiseActivity',['../classgrpc__core_1_1promise__detail_1_1_promise_activity.html',1,'grpc_core::promise_detail']]],
  ['promiseendpoint_180',['PromiseEndpoint',['../classgrpc__core_1_1_promise_endpoint.html',1,'grpc_core::PromiseEndpoint'],['../classgrpc__core_1_1_promise_endpoint.html#aeda604c2bc5b9ff5d28493ee242504af',1,'grpc_core::PromiseEndpoint::PromiseEndpoint()']]],
  ['promiselike_181',['PromiseLike',['../classgrpc__core_1_1promise__detail_1_1_promise_like.html',1,'grpc_core::promise_detail']]],
  ['promiselike_3c_20a_20_3e_182',['PromiseLike&lt; A &gt;',['../classgrpc__core_1_1promise__detail_1_1_promise_like.html',1,'grpc_core::promise_detail']]],
  ['promiselike_3c_20b_20_3e_183',['PromiseLike&lt; B &gt;',['../classgrpc__core_1_1promise__detail_1_1_promise_like.html',1,'grpc_core::promise_detail']]],
  ['promiselike_3c_20c_20_3e_184',['PromiseLike&lt; C &gt;',['../classgrpc__core_1_1promise__detail_1_1_promise_like.html',1,'grpc_core::promise_detail']]],
  ['promiselike_3c_20f_2c_20absl_3a_3aenable_5fif_5ft_3c_20std_3a_3ais_5fvoid_3c_20std_3a_3ainvoke_5fresult_5ft_3c_20f_20_3e_20_3e_3a_3avalue_20_3e_20_3e_185',['PromiseLike&lt; F, absl::enable_if_t&lt; std::is_void&lt; std::invoke_result_t&lt; F &gt; &gt;::value &gt; &gt;',['../classgrpc__core_1_1promise__detail_1_1_promise_like_3_01_f_00_01absl_1_1enable__if__t_3_01std_1_01945764b428d9e394ae6bcad8ba2066.html',1,'grpc_core::promise_detail']]],
  ['promiselike_3c_20f_2c_20absl_3a_3aenable_5fif_5ft_3c_21std_3a_3ais_5fvoid_3c_20std_3a_3ainvoke_5fresult_5ft_3c_20f_20_3e_20_3e_3a_3avalue_20_3e_20_3e_186',['PromiseLike&lt; F, absl::enable_if_t&lt;!std::is_void&lt; std::invoke_result_t&lt; F &gt; &gt;::value &gt; &gt;',['../classgrpc__core_1_1promise__detail_1_1_promise_like_3_01_f_00_01absl_1_1enable__if__t_3_9std_1_19b97298d3c223310ce5e46e3e9c72b0b.html',1,'grpc_core::promise_detail']]],
  ['promiselike_3c_20p_20_3e_187',['PromiseLike&lt; P &gt;',['../classgrpc__core_1_1promise__detail_1_1_promise_like.html',1,'grpc_core::promise_detail']]],
  ['promiselike_3c_20p0_20_3e_188',['PromiseLike&lt; P0 &gt;',['../classgrpc__core_1_1promise__detail_1_1_promise_like.html',1,'grpc_core::promise_detail']]],
  ['promiselike_3c_20p1_20_3e_189',['PromiseLike&lt; P1 &gt;',['../classgrpc__core_1_1promise__detail_1_1_promise_like.html',1,'grpc_core::promise_detail']]],
  ['promiselike_3c_20p2_20_3e_190',['PromiseLike&lt; P2 &gt;',['../classgrpc__core_1_1promise__detail_1_1_promise_like.html',1,'grpc_core::promise_detail']]],
  ['promiselike_3c_20p3_20_3e_191',['PromiseLike&lt; P3 &gt;',['../classgrpc__core_1_1promise__detail_1_1_promise_like.html',1,'grpc_core::promise_detail']]],
  ['promiselike_3c_20p4_20_3e_192',['PromiseLike&lt; P4 &gt;',['../classgrpc__core_1_1promise__detail_1_1_promise_like.html',1,'grpc_core::promise_detail']]],
  ['promiselike_3c_20p5_20_3e_193',['PromiseLike&lt; P5 &gt;',['../classgrpc__core_1_1promise__detail_1_1_promise_like.html',1,'grpc_core::promise_detail']]],
  ['promiselike_3c_20p6_20_3e_194',['PromiseLike&lt; P6 &gt;',['../classgrpc__core_1_1promise__detail_1_1_promise_like.html',1,'grpc_core::promise_detail']]],
  ['promiselike_3c_20p7_20_3e_195',['PromiseLike&lt; P7 &gt;',['../classgrpc__core_1_1promise__detail_1_1_promise_like.html',1,'grpc_core::promise_detail']]],
  ['promiselike_3c_20p8_20_3e_196',['PromiseLike&lt; P8 &gt;',['../classgrpc__core_1_1promise__detail_1_1_promise_like.html',1,'grpc_core::promise_detail']]],
  ['promiselike_3c_20prioritizedrace_3c_20promises_2e_2e_2e_20_3e_20_3e_197',['PromiseLike&lt; PrioritizedRace&lt; Promises... &gt; &gt;',['../classgrpc__core_1_1promise__detail_1_1_promise_like.html',1,'grpc_core::promise_detail']]],
  ['promiselike_3c_20promise_20_3e_198',['PromiseLike&lt; Promise &gt;',['../classgrpc__core_1_1promise__detail_1_1_promise_like.html',1,'grpc_core::promise_detail']]],
  ['promisemutex_199',['PromiseMutex',['../classgrpc__core_1_1_promise_mutex.html',1,'grpc_core']]],
  ['promisevariant_200',['PromiseVariant',['../classgrpc__core_1_1promise__detail_1_1_promise_variant.html',1,'grpc_core::promise_detail']]],
  ['properties_201',['MSBuild Properties',['../md_src_2csharp_2_b_u_i_l_d-_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md42',1,'']]],
  ['property_20pages_202',['Visual Studio property pages',['../md_src_2csharp_2_grpc_8_tools_2implementation__notes.html#autotoc_md73',1,'']]],
  ['props_20and_20target_20files_203',['.props and .target files',['../md_src_2csharp_2_grpc_8_tools_2implementation__notes.html#autotoc_md72',1,'']]],
  ['proto_20and_20grpc_20c_20sources_20from_20proto_20files_20no_20c_20compile_204',['&lt;a name=&quot;nocompile&quot;&gt;&lt;/a&gt;Generate proto and gRPC C# sources from .proto files (no C# compile)',['../md_src_2csharp_2_b_u_i_l_d-_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md55',1,'']]],
  ['proto_20files_205',['proto files',['../md_src_2csharp_2_grpc_8_tools_2implementation__notes.html#autotoc_md87',1,'Automatically including .proto files'],['../md_src_2csharp_2_grpc_8_tools_2implementation__notes.html#autotoc_md84',1,'Compile the .proto files']]],
  ['proto_20files_20no_20c_20compile_206',['&lt;a name=&quot;nocompile&quot;&gt;&lt;/a&gt;Generate proto and gRPC C# sources from .proto files (no C# compile)',['../md_src_2csharp_2_b_u_i_l_d-_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md55',1,'']]],
  ['proto_20files_20to_20compile_207',['Prepare the list of .proto files to compile',['../md_src_2csharp_2_grpc_8_tools_2implementation__notes.html#autotoc_md80',1,'']]],
  ['proto_20format_208',['Write your API declaration in proto format',['..//Users/nikhil/Programming/GitHub/grpc/src/objective-c/README.md#autotoc_md104',1,'']]],
  ['proto_20library_20in_20your_20project_209',['Integrate a proto library in your project',['..//Users/nikhil/Programming/GitHub/grpc/src/objective-c/README.md#autotoc_md105',1,'']]],
  ['proto_20only_20nuget_20a_20including_20tt_20proto_20tt_20files_20in_20nuget_20packages_210',['&lt;a name=&quot;proto-only-nuget&quot;&gt;&lt;/a&gt;Including &lt;tt&gt;.proto&lt;/tt&gt; files in NuGet packages',['../md_src_2csharp_2_b_u_i_l_d-_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md65',1,'']]],
  ['proto_20tt_20file_20options_211',['&lt;a name=&quot;visualstudio&quot;&gt;&lt;/a&gt;Visual Studio: setting per-file &lt;tt&gt;.proto&lt;/tt&gt; file options',['../md_src_2csharp_2_b_u_i_l_d-_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md57',1,'']]],
  ['proto_20tt_20files_212',['proto tt files',['../md_src_2csharp_2_b_u_i_l_d-_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md48',1,'&lt;a name=&quot;AdditionalImportDirs&quot;&gt;&lt;/a&gt;AdditionalImportDirs - Setting location of imported &lt;tt&gt;.proto&lt;/tt&gt; files'],['../md_src_2csharp_2_b_u_i_l_d-_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md53',1,'&lt;a name=&quot;autoinclude&quot;&gt;&lt;/a&gt;Automatically including &lt;tt&gt;.proto&lt;/tt&gt; files'],['../md_src_2csharp_2_b_u_i_l_d-_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md45',1,'&lt;a name=&quot;ProtoRoot&quot;&gt;&lt;/a&gt;ProtoRoot - Common root for one or more &lt;tt&gt;.proto&lt;/tt&gt; files']]],
  ['proto_20tt_20files_20between_20multiple_20projects_20in_20the_20same_20vs_20solution_213',['Sharing &lt;tt&gt;.proto&lt;/tt&gt; files between multiple projects (in the same VS solution)',['../md_src_2csharp_2_b_u_i_l_d-_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md35',1,'']]],
  ['proto_20tt_20files_20in_20nuget_20packages_214',['&lt;a name=&quot;proto-only-nuget&quot;&gt;&lt;/a&gt;Including &lt;tt&gt;.proto&lt;/tt&gt; files in NuGet packages',['../md_src_2csharp_2_b_u_i_l_d-_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md65',1,'']]],
  ['proto_20tt_20files_20to_20a_20project_215',['Adding &lt;tt&gt;.proto&lt;/tt&gt; files to a project',['../md_src_2csharp_2_b_u_i_l_d-_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md34',1,'']]],
  ['proto_20tt_20with_20msbuild_20links_216',['Sharing &lt;tt&gt;.proto&lt;/tt&gt; with MSBuild links',['../md_src_2csharp_2_b_u_i_l_d-_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md36',1,'']]],
  ['protobuf_217',['Protobuf',['../class_grpc_1_1_tools_1_1_proto_compile.html#a9e9498924a477236ca523f7a8edb52bf',1,'Grpc.Tools.ProtoCompile.Protobuf'],['../class_grpc_1_1_tools_1_1_proto_compiler_outputs.html#a4396406fc6250663f14a2586eb312507',1,'Grpc.Tools.ProtoCompilerOutputs.Protobuf'],['../class_grpc_1_1_tools_1_1_proto_read_dependencies.html#a1d3c4a107618b08471a4698a05d0220d',1,'Grpc.Tools.ProtoReadDependencies.Protobuf'],['..//Users/nikhil/Programming/GitHub/grpc/src/objective-c/README.md#autotoc_md107',1,'Use gRPC without Protobuf']]],
  ['protobuf_20compiler_20and_20c_20grpc_20plugin_20binaries_218',['Protobuf compiler and C# gRPC plugin binaries',['../md_src_2csharp_2_grpc_8_tools_2implementation__notes.html#autotoc_md75',1,'']]],
  ['protobuf_20item_20metadata_20reference_219',['Protobuf item metadata reference',['../md_src_2csharp_2_b_u_i_l_d-_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md39',1,'']]],
  ['protobuf_20tt_20runtime_20library_220',['&lt;tt&gt;protobuf&lt;/tt&gt; runtime library',['..//Users/nikhil/Programming/GitHub/grpc/src/php/README.md#autotoc_md140',1,'']]],
  ['protobuffile_221',['ProtoBufFile',['../class_proto_buf_file.html',1,'']]],
  ['protobufmethod_222',['ProtoBufMethod',['../class_proto_buf_method.html',1,'']]],
  ['protobufprinter_223',['ProtoBufPrinter',['../class_proto_buf_printer.html',1,'']]],
  ['protobufservice_224',['ProtoBufService',['../class_proto_buf_service.html',1,'']]],
  ['protoc_20em_20and_20the_20grpc_20plugin_20without_20using_20homebrew_225',['Install &lt;em&gt;protoc&lt;/em&gt; and the gRPC plugin without using Homebrew',['..//Users/nikhil/Programming/GitHub/grpc/src/objective-c/README.md#autotoc_md110',1,'']]],
  ['protoc_20em_20with_20the_20grpc_20plugin_226',['Install &lt;em&gt;protoc&lt;/em&gt; with the gRPC plugin',['..//Users/nikhil/Programming/GitHub/grpc/src/objective-c/README.md#autotoc_md109',1,'']]],
  ['protoc_20plugin_227',['&lt;tt&gt;grpc_php_plugin&lt;/tt&gt; protoc plugin',['..//Users/nikhil/Programming/GitHub/grpc/src/php/README.md#autotoc_md139',1,'']]],
  ['protoc_20tt_20compiler_228',['&lt;tt&gt;protoc&lt;/tt&gt; compiler',['..//Users/nikhil/Programming/GitHub/grpc/src/php/README.md#autotoc_md138',1,'']]],
  ['protocol_20buffers_229',['Protocol Buffers',['..//Users/nikhil/Programming/GitHub/grpc/src/php/README.md#autotoc_md137',1,'']]],
  ['protocol_20buffers_20compiler_20explicitly_230',['&lt;a name=&quot;compiler&quot;&gt;&lt;/a&gt;Bypassing Grpc.Tools to run the protocol buffers compiler explicitly',['../md_src_2csharp_2_b_u_i_l_d-_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md61',1,'']]],
  ['protocol_20buffers_20grpc_20codegen_20integration_20into_20net_20build_231',['Protocol Buffers/gRPC Codegen Integration Into .NET Build',['../md_src_2csharp_2_b_u_i_l_d-_i_n_t_e_g_r_a_t_i_o_n.html',1,'']]],
  ['protocol_20buffers_20messages_232',['&lt;a name=&quot;grpcservices&quot;&gt;&lt;/a&gt;GrpcServices - Generating gRPC services and protocol buffers messages',['../md_src_2csharp_2_b_u_i_l_d-_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md50',1,'']]],
  ['protocol_5fcontext_233',['protocol_context',['../classgrpc_1_1beta_1_1__client__adaptations_1_1___rendezvous.html#ae415101ba804f732af7391433a7cd266',1,'grpc.beta._client_adaptations._Rendezvous.protocol_context()'],['../classgrpc_1_1beta_1_1__server__adaptations_1_1___face_servicer_context.html#aefb7c202192c5f45321d6523e5361c6a',1,'grpc.beta._server_adaptations._FaceServicerContext.protocol_context()'],['../classgrpc_1_1framework_1_1interfaces_1_1face_1_1face_1_1_rpc_context.html#aed6f43acc06010573f5feda70f0d08bc',1,'grpc.framework.interfaces.face.face.RpcContext.protocol_context()']]],
  ['protocolreceiver_234',['ProtocolReceiver',['../classgrpc_1_1framework_1_1interfaces_1_1base_1_1base_1_1_protocol_receiver.html',1,'grpc::framework::interfaces::base::base']]],
  ['protocompile_235',['ProtoCompile',['../class_grpc_1_1_tools_1_1_proto_compile.html',1,'Grpc::Tools']]],
  ['protocompilebasictest_236',['ProtoCompileBasicTest',['../class_grpc_1_1_tools_1_1_tests_1_1_proto_compile_basic_test.html',1,'Grpc::Tools::Tests']]],
  ['protocompilecommandlinegeneratortest_237',['ProtoCompileCommandLineGeneratorTest',['../class_grpc_1_1_tools_1_1_tests_1_1_proto_compile_command_line_generator_test.html',1,'Grpc::Tools::Tests']]],
  ['protocompilecommandlineprintertest_238',['ProtoCompileCommandLinePrinterTest',['../class_grpc_1_1_tools_1_1_tests_1_1_proto_compile_command_line_printer_test.html',1,'Grpc::Tools::Tests']]],
  ['protocompileroutputs_239',['ProtoCompilerOutputs',['../class_grpc_1_1_tools_1_1_proto_compiler_outputs.html',1,'Grpc::Tools']]],
  ['protocompiletestable_240',['ProtoCompileTestable',['../class_grpc_1_1_tools_1_1_tests_1_1_proto_compile_basic_test_1_1_proto_compile_testable.html',1,'Grpc::Tools::Tests::ProtoCompileBasicTest']]],
  ['protodepdir_241',['ProtoDepDir',['../class_grpc_1_1_tools_1_1_proto_compile.html#a72a1e493d3dfba44185c74e69f01ace4',1,'Grpc.Tools.ProtoCompile.ProtoDepDir'],['../class_grpc_1_1_tools_1_1_proto_read_dependencies.html#a90830d203cee1c618e7577a74faa8906',1,'Grpc.Tools.ProtoReadDependencies.ProtoDepDir']]],
  ['protofiles_242',['ProtoFiles',['../class_grpc_1_1_tools_1_1_tests_1_1_ms_build_integration_test_1_1_results.html#a7234c280b221c8c016ea8c3634fff3f1',1,'Grpc::Tools::Tests::MsBuildIntegrationTest::Results']]],
  ['protomethod_243',['ProtoMethod',['../class_proto_method.html',1,'']]],
  ['protopath_244',['ProtoPath',['../class_grpc_1_1_tools_1_1_proto_compile.html#ab24cab94d3fe288b6ad7a4e139838db6',1,'Grpc::Tools::ProtoCompile']]],
  ['protoreaddependencies_245',['ProtoReadDependencies',['../class_grpc_1_1_tools_1_1_proto_read_dependencies.html',1,'Grpc::Tools']]],
  ['protoreflectiondescriptordatabase_246',['ProtoReflectionDescriptorDatabase',['../classgrpc__reflection_1_1v1alpha_1_1proto__reflection__descriptor__database_1_1_proto_reflection_descriptor_database.html',1,'grpc_reflection::v1alpha::proto_reflection_descriptor_database']]],
  ['protoroot_20a_20protoroot_20common_20root_20for_20one_20or_20more_20tt_20proto_20tt_20files_247',['&lt;a name=&quot;ProtoRoot&quot;&gt;&lt;/a&gt;ProtoRoot - Common root for one or more &lt;tt&gt;.proto&lt;/tt&gt; files',['../md_src_2csharp_2_b_u_i_l_d-_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md45',1,'']]],
  ['protoroot_20common_20root_20for_20one_20or_20more_20tt_20proto_20tt_20files_248',['&lt;a name=&quot;ProtoRoot&quot;&gt;&lt;/a&gt;ProtoRoot - Common root for one or more &lt;tt&gt;.proto&lt;/tt&gt; files',['../md_src_2csharp_2_b_u_i_l_d-_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md45',1,'']]],
  ['protoroot_20tt_249',['Example use of &lt;tt&gt;ProtoRoot&lt;/tt&gt;',['../md_src_2csharp_2_b_u_i_l_d-_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md46',1,'']]],
  ['protorpc_250',['ProtoRPC',['../class_proto_r_p_c.html',1,'']]],
  ['protos_20tt_20and_20tt_20outsideprojectprotos_20tt_251',['&lt;tt&gt;ProjectFolder\\Protos&lt;/tt&gt; and &lt;tt&gt;..\\OutsideProjectProtos&lt;/tt&gt;',['../md_src_2csharp_2_b_u_i_l_d-_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md47',1,'']]],
  ['protoserverreflection_252',['ProtoServerReflection',['../classgrpc_1_1_proto_server_reflection.html',1,'grpc']]],
  ['protoserverreflectionbackend_253',['ProtoServerReflectionBackend',['../classgrpc_1_1_proto_server_reflection_backend.html',1,'grpc']]],
  ['protoserverreflectionv1_254',['ProtoServerReflectionV1',['../classgrpc_1_1_proto_server_reflection_v1.html',1,'grpc']]],
  ['protoservice_255',['ProtoService',['../class_proto_service.html',1,'']]],
  ['protoservice_28legacy_29_256',['ProtoService(Legacy)',['../category_proto_service_07_legacy_08.html',1,'']]],
  ['protostreamframe_257',['ProtoStreamFrame',['../structgrpc__core_1_1chaotic__good_1_1_proto_stream_frame.html',1,'grpc_core::chaotic_good::ProtoStreamFrame&lt; frame_type, Body &gt;'],['../structgrpc__core_1_1chaotic__good__legacy_1_1_proto_stream_frame.html',1,'grpc_core::chaotic_good_legacy::ProtoStreamFrame&lt; frame_type, Body &gt;']]],
  ['protostreamframe_3c_20frametype_3a_3akbeginmessage_2c_20chaotic_5fgood_5fframe_3a_3abeginmessage_20_3e_258',['ProtoStreamFrame&lt; FrameType::kBeginMessage, chaotic_good_frame::BeginMessage &gt;',['../structgrpc__core_1_1chaotic__good_1_1_proto_stream_frame.html',1,'grpc_core::chaotic_good::ProtoStreamFrame&lt; FrameType::kBeginMessage, chaotic_good_frame::BeginMessage &gt;'],['../structgrpc__core_1_1chaotic__good__legacy_1_1_proto_stream_frame.html',1,'grpc_core::chaotic_good_legacy::ProtoStreamFrame&lt; FrameType::kBeginMessage, chaotic_good_frame::BeginMessage &gt;']]],
  ['protostreamframe_3c_20frametype_3a_3akclientinitialmetadata_2c_20chaotic_5fgood_5fframe_3a_3aclientmetadata_20_3e_259',['ProtoStreamFrame&lt; FrameType::kClientInitialMetadata, chaotic_good_frame::ClientMetadata &gt;',['../structgrpc__core_1_1chaotic__good_1_1_proto_stream_frame.html',1,'grpc_core::chaotic_good::ProtoStreamFrame&lt; FrameType::kClientInitialMetadata, chaotic_good_frame::ClientMetadata &gt;'],['../structgrpc__core_1_1chaotic__good__legacy_1_1_proto_stream_frame.html',1,'grpc_core::chaotic_good_legacy::ProtoStreamFrame&lt; FrameType::kClientInitialMetadata, chaotic_good_frame::ClientMetadata &gt;']]],
  ['protostreamframe_3c_20frametype_3a_3akserverinitialmetadata_2c_20chaotic_5fgood_5fframe_3a_3aservermetadata_20_3e_260',['ProtoStreamFrame&lt; FrameType::kServerInitialMetadata, chaotic_good_frame::ServerMetadata &gt;',['../structgrpc__core_1_1chaotic__good_1_1_proto_stream_frame.html',1,'grpc_core::chaotic_good::ProtoStreamFrame&lt; FrameType::kServerInitialMetadata, chaotic_good_frame::ServerMetadata &gt;'],['../structgrpc__core_1_1chaotic__good__legacy_1_1_proto_stream_frame.html',1,'grpc_core::chaotic_good_legacy::ProtoStreamFrame&lt; FrameType::kServerInitialMetadata, chaotic_good_frame::ServerMetadata &gt;']]],
  ['protostreamframe_3c_20frametype_3a_3akservertrailingmetadata_2c_20chaotic_5fgood_5fframe_3a_3aservermetadata_20_3e_261',['ProtoStreamFrame&lt; FrameType::kServerTrailingMetadata, chaotic_good_frame::ServerMetadata &gt;',['../structgrpc__core_1_1chaotic__good_1_1_proto_stream_frame.html',1,'grpc_core::chaotic_good::ProtoStreamFrame&lt; FrameType::kServerTrailingMetadata, chaotic_good_frame::ServerMetadata &gt;'],['../structgrpc__core_1_1chaotic__good__legacy_1_1_proto_stream_frame.html',1,'grpc_core::chaotic_good_legacy::ProtoStreamFrame&lt; FrameType::kServerTrailingMetadata, chaotic_good_frame::ServerMetadata &gt;']]],
  ['prototoolsplatform_262',['ProtoToolsPlatform',['../class_grpc_1_1_tools_1_1_proto_tools_platform.html',1,'Grpc::Tools']]],
  ['prototoolsplatformtasktest_263',['ProtoToolsPlatformTaskTest',['../class_grpc_1_1_tools_1_1_tests_1_1_proto_tools_platform_task_test.html',1,'Grpc::Tools::Tests']]],
  ['prototransportframe_264',['ProtoTransportFrame',['../structgrpc__core_1_1chaotic__good_1_1_proto_transport_frame.html',1,'grpc_core::chaotic_good::ProtoTransportFrame&lt; frame_type, Body &gt;'],['../structgrpc__core_1_1chaotic__good__legacy_1_1_proto_transport_frame.html',1,'grpc_core::chaotic_good_legacy::ProtoTransportFrame&lt; frame_type, Body &gt;']]],
  ['prototransportframe_3c_20frametype_3a_3aksettings_2c_20chaotic_5fgood_5fframe_3a_3asettings_20_3e_265',['ProtoTransportFrame&lt; FrameType::kSettings, chaotic_good_frame::Settings &gt;',['../structgrpc__core_1_1chaotic__good_1_1_proto_transport_frame.html',1,'grpc_core::chaotic_good::ProtoTransportFrame&lt; FrameType::kSettings, chaotic_good_frame::Settings &gt;'],['../structgrpc__core_1_1chaotic__good__legacy_1_1_proto_transport_frame.html',1,'grpc_core::chaotic_good_legacy::ProtoTransportFrame&lt; FrameType::kSettings, chaotic_good_frame::Settings &gt;']]],
  ['proxyclientserviceclient_266',['ProxyClientServiceClient',['../class_grpc_1_1_testing_1_1_proxy_client_service_client.html',1,'Grpc::Testing']]],
  ['proxymapperinterface_267',['ProxyMapperInterface',['../classgrpc__core_1_1_proxy_mapper_interface.html',1,'grpc_core']]],
  ['proxymapperregistry_268',['ProxyMapperRegistry',['../classgrpc__core_1_1_proxy_mapper_registry.html',1,'grpc_core']]],
  ['proxyservice_269',['ProxyService',['../class_g_p_b_metadata_1_1_src_1_1_proto_1_1_grpc_1_1_testing_1_1_proxy_service.html',1,'GPBMetadata::Src::Proto::Grpc::Testing']]],
  ['proxystat_270',['ProxyStat',['../class_grpc_1_1_testing_1_1_proxy_stat.html',1,'Grpc::Testing']]],
  ['publishtoappencoder_271',['PublishToAppEncoder',['../classgrpc__core_1_1_publish_to_app_encoder.html',1,'grpc_core']]],
  ['push_272',['Push',['../classgrpc__core_1_1pipe__detail_1_1_push.html',1,'grpc_core::pipe_detail']]],
  ['put_273',['Put',['../classtsi_1_1_ssl_session_l_r_u_cache.html#ace1dae2455003a7cca6ac12ff195f7fa',1,'tsi::SslSessionLRUCache']]],
  ['putting_20symbols_20into_20action_20example_20gdb_20workflow_274',['Putting symbols into action (example gdb workflow)',['..//Users/nikhil/Programming/GitHub/grpc/src/ruby/nativedebug/README.md#autotoc_md173',1,'']]],
  ['python_275',['Python',['../md_src_2python_2_c_o_n_t_r_i_b_u_t_i_n_g.html',1,'Contributing to gRPC Python'],['../md_src_2python_2_c_o_n_t_r_i_b_u_t_i_n_g.html#autotoc_md165',1,'Steps to Contributing to gRPC Python'],['../md_src_2python_2_c_o_n_t_r_i_b_u_t_i_n_g.html#autotoc_md163',1,'Writing Your First Patch for gRPC Python']]],
  ['pythoncensuscontext_276',['PythonCensusContext',['../classgrpc__observability_1_1_python_census_context.html',1,'grpc_observability']]],
  ['pythongrpcgenerator_277',['PythonGrpcGenerator',['../classgrpc__python__generator_1_1_python_grpc_generator.html',1,'grpc_python_generator']]],
  ['pythonlabelsinjector_278',['PythonLabelsInjector',['../classgrpc__observability_1_1_python_labels_injector.html',1,'grpc_observability']]],
  ['pythonopencensuscallattempttracer_279',['PythonOpenCensusCallAttemptTracer',['../classgrpc__observability_1_1_python_open_census_call_tracer_1_1_python_open_census_call_attempt_tracer.html',1,'grpc_observability::PythonOpenCensusCallTracer']]],
  ['pythonopencensuscalltracer_280',['PythonOpenCensusCallTracer',['../classgrpc__observability_1_1_python_open_census_call_tracer.html',1,'grpc_observability']]],
  ['pythonopencensusservercalltracer_281',['PythonOpenCensusServerCallTracer',['../classgrpc__observability_1_1_python_open_census_server_call_tracer.html',1,'grpc_observability']]],
  ['pythonopencensusservercalltracerfactory_282',['PythonOpenCensusServerCallTracerFactory',['../classgrpc__observability_1_1_python_open_census_server_call_tracer_factory.html',1,'grpc_observability']]],
  ['pythonplugintest_283',['PythonPluginTest',['../classtests_1_1protoc__plugin_1_1__python__plugin__test_1_1_python_plugin_test.html',1,'tests.protoc_plugin._python_plugin_test.PythonPluginTest'],['../classtests_1_1protoc__plugin_1_1beta__python__plugin__test_1_1_python_plugin_test.html',1,'tests.protoc_plugin.beta_python_plugin_test.PythonPluginTest']]]
];
