var searchData=
[
  ['label_0',['Label',['../structgrpc_1_1internal_1_1_open_census_registry_1_1_label.html',1,'grpc::internal::OpenCensusRegistry::Label'],['../structgrpc__observability_1_1_label.html',1,'grpc_observability::Label']]],
  ['labelsinjector_1',['LabelsInjector',['../classgrpc_1_1internal_1_1_labels_injector.html',1,'grpc::internal']]],
  ['labelsiterable_2',['LabelsIterable',['../classgrpc_1_1internal_1_1_labels_iterable.html',1,'grpc::internal']]],
  ['lameclientfilter_3',['LameClientFilter',['../classgrpc__core_1_1_lame_client_filter.html',1,'grpc_core']]],
  ['last_5fnew_5fstream_5fid_4',['last_new_stream_id',['../structgrpc__chttp2__transport.html#a5b61de7221b8029e82e48169d079fd84',1,'grpc_chttp2_transport']]],
  ['latch_5',['Latch',['../classgrpc__core_1_1_latch.html',1,'grpc_core']]],
  ['latch_3c_20bool_20_3e_6',['Latch&lt; bool &gt;',['../classgrpc__core_1_1_latch.html',1,'grpc_core']]],
  ['latch_3c_20grpc_5fpolling_5fentity_20_3e_7',['Latch&lt; grpc_polling_entity &gt;',['../classgrpc__core_1_1_latch.html',1,'grpc_core']]],
  ['latch_3c_20void_20_3e_8',['Latch&lt; void &gt;',['../classgrpc__core_1_1_latch_3_01void_01_4.html',1,'grpc_core']]],
  ['layout_9',['Layout',['../structgrpc__core_1_1filters__detail_1_1_layout.html',1,'grpc_core::filters_detail']]],
  ['layout_3c_20clientmetadatahandle_20_3e_10',['Layout&lt; ClientMetadataHandle &gt;',['../structgrpc__core_1_1filters__detail_1_1_layout.html',1,'grpc_core::filters_detail']]],
  ['layout_3c_20messagehandle_20_3e_11',['Layout&lt; MessageHandle &gt;',['../structgrpc__core_1_1filters__detail_1_1_layout.html',1,'grpc_core::filters_detail']]],
  ['layout_3c_20servermetadatahandle_20_3e_12',['Layout&lt; ServerMetadataHandle &gt;',['../structgrpc__core_1_1filters__detail_1_1_layout.html',1,'grpc_core::filters_detail']]],
  ['lbcallstate_13',['LbCallState',['../classgrpc__core_1_1_client_channel_filter_1_1_load_balanced_call_1_1_lb_call_state.html',1,'grpc_core::ClientChannelFilter::LoadBalancedCall']]],
  ['lbcostbinmetadata_14',['LbCostBinMetadata',['../structgrpc__core_1_1_lb_cost_bin_metadata.html',1,'grpc_core']]],
  ['lbmetadata_15',['LbMetadata',['../classgrpc__core_1_1_lb_metadata.html',1,'grpc_core']]],
  ['lbqueuedcallcanceller_16',['LbQueuedCallCanceller',['../classgrpc__core_1_1_client_channel_filter_1_1_filter_based_load_balanced_call_1_1_lb_queued_call_canceller.html',1,'grpc_core::ClientChannelFilter::FilterBasedLoadBalancedCall']]],
  ['lbtokenmetadata_17',['LbTokenMetadata',['../structgrpc__core_1_1_lb_token_metadata.html',1,'grpc_core']]],
  ['legacycalldata_18',['LegacyCallData',['../classgrpc__core_1_1_retry_filter_1_1_legacy_call_data.html',1,'grpc_core::RetryFilter']]],
  ['legacychannel_19',['LegacyChannel',['../classgrpc__core_1_1_legacy_channel.html',1,'grpc_core']]],
  ['legacychannelidlefilter_20',['LegacyChannelIdleFilter',['../classgrpc__core_1_1_legacy_channel_idle_filter.html',1,'grpc_core']]],
  ['legacyclientauthfilter_21',['LegacyClientAuthFilter',['../classgrpc__core_1_1_legacy_client_auth_filter.html',1,'grpc_core']]],
  ['legacyclientidlefilter_22',['LegacyClientIdleFilter',['../classgrpc__core_1_1_legacy_client_idle_filter.html',1,'grpc_core']]],
  ['legacyconnectedsubchannel_23',['LegacyConnectedSubchannel',['../classgrpc__core_1_1_legacy_connected_subchannel.html',1,'grpc_core']]],
  ['legacyglobalsubchannelpool_24',['LegacyGlobalSubchannelPool',['../classgrpc__core_1_1_legacy_global_subchannel_pool.html',1,'grpc_core']]],
  ['legacymaxagefilter_25',['LegacyMaxAgeFilter',['../classgrpc__core_1_1_legacy_max_age_filter.html',1,'grpc_core']]],
  ['legal_20requirements_26',['Legal Requirements',['../md_src_2python_2_c_o_n_t_r_i_b_u_t_i_n_g.html#autotoc_md159',1,'']]],
  ['length_27',['Length',['../classgrpc__core_1_1_slice_buffer.html#a772167d945eb76972ebc08d13d4f0861',1,'grpc_core::SliceBuffer']]],
  ['less_28',['Less',['../structgrpc__core_1_1_backend_metric_propagation_1_1_less.html',1,'grpc_core::BackendMetricPropagation::Less'],['../structgrpc__core_1_1_xds_locality_name_1_1_less.html',1,'grpc_core::XdsLocalityName::Less']]],
  ['library_29',['library',['..//Users/nikhil/Programming/GitHub/grpc/src/php/README.md#autotoc_md140',1,'&lt;tt&gt;protobuf&lt;/tt&gt; runtime library'],['..//Users/nikhil/Programming/GitHub/grpc/src/php/README.md#autotoc_md133',1,'Build the gRPC C core library'],['../md_src_2csharp_2_b_u_i_l_d-_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md37',1,'Generating code in a class library']]],
  ['library_20in_20your_20code_30',['Use the generated library in your code',['..//Users/nikhil/Programming/GitHub/grpc/src/objective-c/README.md#autotoc_md106',1,'']]],
  ['library_20in_20your_20project_31',['Integrate a proto library in your project',['..//Users/nikhil/Programming/GitHub/grpc/src/objective-c/README.md#autotoc_md105',1,'']]],
  ['library_20s_20resolution_20to_20tcp_20socket_20issues_32',['gRPC iOS library&apos;s resolution to TCP socket issues',['../md_src_2objective-c_2_network_transition_behavior.html#autotoc_md97',1,'']]],
  ['library_20without_20using_20cocoapods_33',['Integrate the generated gRPC library without using Cocoapods',['..//Users/nikhil/Programming/GitHub/grpc/src/objective-c/README.md#autotoc_md111',1,'']]],
  ['line_20options_34',['&lt;tt&gt;grpc_csharp_plugin&lt;/tt&gt; command line options',['../md_src_2csharp_2_b_u_i_l_d-_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md40',1,'']]],
  ['links_35',['Sharing &lt;tt&gt;.proto&lt;/tt&gt; with MSBuild links',['../md_src_2csharp_2_b_u_i_l_d-_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md36',1,'']]],
  ['list_20of_20files_20for_20the_20c_20compiler_36',['Add generated .cs files to the list of files for the C# compiler',['../md_src_2csharp_2_grpc_8_tools_2implementation__notes.html#autotoc_md85',1,'']]],
  ['list_20of_20proto_20files_20to_20compile_37',['Prepare the list of .proto files to compile',['../md_src_2csharp_2_grpc_8_tools_2implementation__notes.html#autotoc_md80',1,'']]],
  ['listenerinterface_38',['ListenerInterface',['../classgrpc__core_1_1_server_1_1_listener_interface.html',1,'grpc_core::Server']]],
  ['listenersocket_39',['ListenerSocket',['../structgrpc__event__engine_1_1experimental_1_1_listener_sockets_container_1_1_listener_socket.html',1,'grpc_event_engine::experimental::ListenerSocketsContainer']]],
  ['listenersocketscontainer_40',['ListenerSocketsContainer',['../classgrpc__event__engine_1_1experimental_1_1_listener_sockets_container.html',1,'grpc_event_engine::experimental']]],
  ['listenerstate_41',['ListenerState',['../classgrpc__core_1_1_server_1_1_listener_state.html',1,'grpc_core::Server']]],
  ['listenersupportsfdextension_42',['ListenerSupportsFdExtension',['../classgrpc__event__engine_1_1experimental_1_1_listener_supports_fd_extension.html',1,'grpc_event_engine::experimental']]],
  ['listenerwatcher_43',['ListenerWatcher',['../classgrpc__core_1_1_xds_dependency_manager_1_1_listener_watcher.html',1,'grpc_core::XdsDependencyManager']]],
  ['listensocketnode_44',['ListenSocketNode',['../classgrpc__core_1_1channelz_1_1_listen_socket_node.html',1,'grpc_core::channelz']]],
  ['lists_45',['lists',['../structgrpc__chttp2__transport.html#a70d937138945c07b53f7be848fb1cc4a',1,'grpc_chttp2_transport']]],
  ['livingthreadcount_46',['LivingThreadCount',['../classgrpc__event__engine_1_1experimental_1_1_living_thread_count.html',1,'grpc_event_engine::experimental']]],
  ['load_20balancing_47',['Load Balancing',['..//Users/nikhil/Programming/GitHub/grpc/src/core/client_channel/README.md#autotoc_md4',1,'']]],
  ['load_5ffrom_5fstring_5fcontent_48',['load_from_string_content',['../classgrpc__observability_1_1__observability__config_1_1_gcp_observability_config.html#a41335865184ea314f9f870f6358b6e88',1,'grpc_observability::_observability_config::GcpObservabilityConfig']]],
  ['loadbalancedcall_49',['LoadBalancedCall',['../classgrpc__core_1_1_client_channel_filter_1_1_load_balanced_call.html',1,'grpc_core::ClientChannelFilter']]],
  ['loadbalancedcalldestination_50',['LoadBalancedCallDestination',['../classgrpc__core_1_1_load_balanced_call_destination.html',1,'grpc_core']]],
  ['loadbalanceraccumulatedstatsrequest_51',['LoadBalancerAccumulatedStatsRequest',['../class_grpc_1_1_testing_1_1_load_balancer_accumulated_stats_request.html',1,'Grpc::Testing']]],
  ['loadbalanceraccumulatedstatsresponse_52',['LoadBalancerAccumulatedStatsResponse',['../class_grpc_1_1_testing_1_1_load_balancer_accumulated_stats_response.html',1,'Grpc::Testing']]],
  ['loadbalancerstatsrequest_53',['LoadBalancerStatsRequest',['../class_grpc_1_1_testing_1_1_load_balancer_stats_request.html',1,'Grpc::Testing']]],
  ['loadbalancerstatsresponse_54',['LoadBalancerStatsResponse',['../class_grpc_1_1_testing_1_1_load_balancer_stats_response.html',1,'Grpc::Testing']]],
  ['loadbalancerstatsservice_55',['LoadBalancerStatsService',['../class_load_balancer_stats_service.html',1,'']]],
  ['loadbalancerstatsserviceclient_56',['LoadBalancerStatsServiceClient',['../class_grpc_1_1_testing_1_1_load_balancer_stats_service_client.html',1,'Grpc::Testing']]],
  ['loadbalancerstatsservicestub_57',['LoadBalancerStatsServiceStub',['../class_grpc_1_1_testing_1_1_load_balancer_stats_service_stub.html',1,'Grpc::Testing']]],
  ['loadbalancingpolicy_58',['LoadBalancingPolicy',['../classgrpc__core_1_1_load_balancing_policy.html',1,'grpc_core']]],
  ['loadbalancingpolicyexists_59',['LoadBalancingPolicyExists',['../classgrpc__core_1_1_load_balancing_policy_registry.html#a3b4256a600b538db360d1b56836dc388',1,'grpc_core::LoadBalancingPolicyRegistry']]],
  ['loadbalancingpolicyfactory_60',['LoadBalancingPolicyFactory',['../classgrpc__core_1_1_load_balancing_policy_factory.html',1,'grpc_core']]],
  ['loadbalancingpolicyregistry_61',['LoadBalancingPolicyRegistry',['../classgrpc__core_1_1_load_balancing_policy_registry.html',1,'grpc_core']]],
  ['loadbool_62',['LoadBool',['../classgrpc__core_1_1json__detail_1_1_load_bool.html',1,'grpc_core::json_detail']]],
  ['loaddatastore_63',['LoadDataStore',['../classgrpc_1_1load__reporter_1_1_load_data_store.html',1,'grpc::load_reporter']]],
  ['loaddouble_64',['LoadDouble',['../classgrpc__core_1_1json__detail_1_1_load_double.html',1,'grpc_core::json_detail']]],
  ['loadduration_65',['LoadDuration',['../classgrpc__core_1_1json__detail_1_1_load_duration.html',1,'grpc_core::json_detail']]],
  ['loader_66',['Loader',['../classtests_1_1__loader_1_1_loader.html',1,'tests::_loader']]],
  ['loaderinterface_67',['LoaderInterface',['../classgrpc__core_1_1json__detail_1_1_loader_interface.html',1,'grpc_core::json_detail']]],
  ['loadfloat_68',['LoadFloat',['../classgrpc__core_1_1json__detail_1_1_load_float.html',1,'grpc_core::json_detail']]],
  ['loadmap_69',['LoadMap',['../classgrpc__core_1_1json__detail_1_1_load_map.html',1,'grpc_core::json_detail']]],
  ['loadnumber_70',['LoadNumber',['../classgrpc__core_1_1json__detail_1_1_load_number.html',1,'grpc_core::json_detail']]],
  ['loadparams_71',['LoadParams',['../class_grpc_1_1_testing_1_1_load_params.html',1,'Grpc::Testing']]],
  ['loadrecordkey_72',['LoadRecordKey',['../classgrpc_1_1load__reporter_1_1_load_record_key.html',1,'grpc::load_reporter']]],
  ['loadrecordvalue_73',['LoadRecordValue',['../classgrpc_1_1load__reporter_1_1_load_record_value.html',1,'grpc::load_reporter']]],
  ['loadreporter_74',['LoadReporter',['../classgrpc_1_1load__reporter_1_1_load_reporter.html',1,'grpc::load_reporter']]],
  ['loadreporterasyncserviceimpl_75',['LoadReporterAsyncServiceImpl',['../classgrpc_1_1load__reporter_1_1_load_reporter_async_service_impl.html',1,'grpc::load_reporter']]],
  ['loadreportingserviceserverbuilderplugin_76',['LoadReportingServiceServerBuilderPlugin',['../classgrpc_1_1load__reporter_1_1_load_reporting_service_server_builder_plugin.html',1,'grpc::load_reporter']]],
  ['loadscalar_77',['LoadScalar',['../classgrpc__core_1_1json__detail_1_1_load_scalar.html',1,'grpc_core::json_detail']]],
  ['loadstring_78',['LoadString',['../classgrpc__core_1_1json__detail_1_1_load_string.html',1,'grpc_core::json_detail']]],
  ['loadtestsfromnames_79',['loadTestsFromNames',['../classtests_1_1__loader_1_1_loader.html#aabd5c45c3110ba9aaf2e6d97a6a4864e',1,'tests::_loader::Loader']]],
  ['loadunprocessedjsonarray_80',['LoadUnprocessedJsonArray',['../classgrpc__core_1_1json__detail_1_1_load_unprocessed_json_array.html',1,'grpc_core::json_detail']]],
  ['loadunprocessedjsonobject_81',['LoadUnprocessedJsonObject',['../classgrpc__core_1_1json__detail_1_1_load_unprocessed_json_object.html',1,'grpc_core::json_detail']]],
  ['loadvector_82',['LoadVector',['../classgrpc__core_1_1json__detail_1_1_load_vector.html',1,'grpc_core::json_detail']]],
  ['loadwrapped_83',['LoadWrapped',['../classgrpc__core_1_1json__detail_1_1_load_wrapped.html',1,'grpc_core::json_detail']]],
  ['local_5fchannel_5fcredentials_84',['local_channel_credentials',['../namespacegrpc.html#ad9d4c44b998b7cc127f48b6ab38fe840',1,'grpc']]],
  ['local_5fserver_5fcredentials_85',['local_server_credentials',['../namespacegrpc.html#a035996523766d2f1da35c4c15ec1d189',1,'grpc']]],
  ['localconnectiontype_86',['LocalConnectionType',['../classgrpc_1_1_local_connection_type.html',1,'grpc']]],
  ['localcredentialstest_87',['LocalCredentialsTest',['../classtests_1_1unit_1_1__local__credentials__test_1_1_local_credentials_test.html',1,'tests::unit::_local_credentials_test']]],
  ['localerror_88',['LocalError',['../classgrpc_1_1framework_1_1interfaces_1_1face_1_1face_1_1_local_error.html',1,'grpc::framework::interfaces::face::face']]],
  ['locality_89',['Locality',['../structgrpc__core_1_1_xds_endpoint_resource_1_1_priority_1_1_locality.html',1,'grpc_core::XdsEndpointResource::Priority']]],
  ['localitystate_90',['LocalityState',['../structgrpc__core_1_1_lrs_client_1_1_load_report_state_1_1_locality_state.html',1,'grpc_core::LrsClient::LoadReportState']]],
  ['localshutdownerror_91',['LocalShutdownError',['../classgrpc_1_1framework_1_1interfaces_1_1face_1_1face_1_1_local_shutdown_error.html',1,'grpc::framework::interfaces::face::face']]],
  ['localsubchannelpool_92',['LocalSubchannelPool',['../classgrpc__core_1_1_local_subchannel_pool.html',1,'grpc_core']]],
  ['location_20of_20imported_20tt_20proto_20tt_20files_93',['&lt;a name=&quot;AdditionalImportDirs&quot;&gt;&lt;/a&gt;AdditionalImportDirs - Setting location of imported &lt;tt&gt;.proto&lt;/tt&gt; files',['../md_src_2csharp_2_b_u_i_l_d-_i_n_t_e_g_r_a_t_i_o_n.html#autotoc_md48',1,'']]],
  ['lock_94',['Lock',['../classgrpc__core_1_1_inter_activity_mutex_1_1_lock.html',1,'grpc_core::InterActivityMutex&lt; T &gt;::Lock'],['../classgrpc__core_1_1_promise_mutex_1_1_lock.html',1,'grpc_core::PromiseMutex&lt; T &gt;::Lock']]],
  ['lockableandreleasablemutexlock_95',['LockableAndReleasableMutexLock',['../classgrpc__core_1_1_lockable_and_releasable_mutex_lock.html',1,'grpc_core']]],
  ['lockedmultiproducersingleconsumerqueue_96',['LockedMultiProducerSingleConsumerQueue',['../classgrpc__core_1_1_locked_multi_producer_single_consumer_queue.html',1,'grpc_core']]],
  ['lockfreeevent_97',['LockfreeEvent',['../classgrpc__core_1_1_lockfree_event.html',1,'grpc_core::LockfreeEvent'],['../classgrpc__event__engine_1_1experimental_1_1_lockfree_event.html',1,'grpc_event_engine::experimental::LockfreeEvent']]],
  ['logcontext_98',['logContext',['../interface_g_r_p_c_call_options.html#afccdd991abd760554d50b2a76e3dfa35',1,'GRPCCallOptions::logContext'],['../interface_g_r_p_c_mutable_call_options.html#a6ad7bf0b79d5f0d25dfa9b8c4011e794',1,'GRPCMutableCallOptions::logContext']]],
  ['logging_99',['Tracing and Logging',['..//Users/nikhil/Programming/GitHub/grpc/src/php/README.md#autotoc_md154',1,'']]],
  ['loggingpooltest_100',['LoggingPoolTest',['../classtests_1_1unit_1_1framework_1_1foundation_1_1__logging__pool__test_1_1_logging_pool_test.html',1,'tests::unit::framework::foundation::_logging_pool_test']]],
  ['loggingsink_101',['LoggingSink',['../classgrpc_1_1internal_1_1_logging_sink.html',1,'grpc::internal::LoggingSink'],['../classgrpc__core_1_1_logging_sink.html',1,'grpc_core::LoggingSink']]],
  ['loggingtest_102',['LoggingTest',['../classtests_1_1unit_1_1__logging__test_1_1_logging_test.html',1,'tests::unit::_logging_test']]],
  ['logicalconnection_103',['LogicalConnection',['../classgrpc__core_1_1_server_1_1_listener_interface_1_1_logical_connection.html',1,'grpc_core::Server::ListenerInterface']]],
  ['logicaldns_104',['LogicalDns',['../structgrpc__core_1_1_xds_cluster_resource_1_1_logical_dns.html',1,'grpc_core::XdsClusterResource']]],
  ['loginfo_105',['LogInfo',['../structgrpc__core_1_1_h_pack_parser_1_1_log_info.html',1,'grpc_core::HPackParser::LogInfo'],['../struct_h_pack_parser_1_1_log_info.html',1,'HPackParser::LogInfo']]],
  ['logwrapper_106',['LogWrapper',['../structgrpc__core_1_1metadata__detail_1_1_log_wrapper.html',1,'grpc_core::metadata_detail']]],
  ['lookupresolverfactory_107',['LookupResolverFactory',['../classgrpc__core_1_1_resolver_registry.html#a4dfea6384e66bf0ab8e7fa85e0c99de6',1,'grpc_core::ResolverRegistry']]],
  ['lookuptaskhandle_108',['LookupTaskHandle',['../structgrpc__core_1_1_d_n_s_resolver_1_1_lookup_task_handle.html',1,'grpc_core::DNSResolver']]],
  ['loop_109',['Loop',['../classgrpc__core_1_1_loop.html',1,'grpc_core']]],
  ['looptraits_110',['LoopTraits',['../structgrpc__core_1_1promise__detail_1_1_loop_traits.html',1,'grpc_core::promise_detail']]],
  ['looptraits_3c_20absl_3a_3astatusor_3c_20loopctl_3c_20absl_3a_3astatus_20_3e_20_3e_20_3e_111',['LoopTraits&lt; absl::StatusOr&lt; LoopCtl&lt; absl::Status &gt; &gt; &gt;',['../structgrpc__core_1_1promise__detail_1_1_loop_traits_3_01absl_1_1_status_or_3_01_loop_ctl_3_01absl_1_1_status_01_4_01_4_01_4.html',1,'grpc_core::promise_detail']]],
  ['looptraits_3c_20absl_3a_3astatusor_3c_20loopctl_3c_20t_20_3e_20_3e_20_3e_112',['LoopTraits&lt; absl::StatusOr&lt; LoopCtl&lt; T &gt; &gt; &gt;',['../structgrpc__core_1_1promise__detail_1_1_loop_traits_3_01absl_1_1_status_or_3_01_loop_ctl_3_01_t_01_4_01_4_01_4.html',1,'grpc_core::promise_detail']]],
  ['looptraits_3c_20loopctl_3c_20t_20_3e_20_3e_113',['LoopTraits&lt; LoopCtl&lt; T &gt; &gt;',['../structgrpc__core_1_1promise__detail_1_1_loop_traits_3_01_loop_ctl_3_01_t_01_4_01_4.html',1,'grpc_core::promise_detail']]],
  ['lrscall_114',['LrsCall',['../classgrpc__core_1_1_lrs_client_1_1_lrs_channel_1_1_lrs_call.html',1,'grpc_core::LrsClient::LrsChannel']]],
  ['lrsclient_115',['LrsClient',['../classgrpc__core_1_1_lrs_client.html',1,'grpc_core']]],
  ['lrucache_116',['LruCache',['../classgrpc__core_1_1_lru_cache.html',1,'grpc_core']]],
  ['lrucache_3c_20std_3a_3astring_2c_20grpc_5fcore_3a_3arefcountedptr_3c_20grpc_5fcall_5fcredentials_20_3e_20_3e_117',['LruCache&lt; std::string, grpc_core::RefCountedPtr&lt; grpc_call_credentials &gt; &gt;',['../classgrpc__core_1_1_lru_cache.html',1,'grpc_core']]]
];
