var searchData=
[
  ['udpa_5fannotations_5ffieldmigrateannotation_0',['udpa_annotations_FieldMigrateAnnotation',['../structudpa__annotations___field_migrate_annotation.html',1,'']]],
  ['udpa_5fannotations_5ffieldsecurityannotation_1',['udpa_annotations_FieldSecurityAnnotation',['../structudpa__annotations___field_security_annotation.html',1,'']]],
  ['udpa_5fannotations_5ffilemigrateannotation_2',['udpa_annotations_FileMigrateAnnotation',['../structudpa__annotations___file_migrate_annotation.html',1,'']]],
  ['udpa_5fannotations_5fmigrateannotation_3',['udpa_annotations_MigrateAnnotation',['../structudpa__annotations___migrate_annotation.html',1,'']]],
  ['udpa_5fannotations_5fstatusannotation_4',['udpa_annotations_StatusAnnotation',['../structudpa__annotations___status_annotation.html',1,'']]],
  ['udpa_5fannotations_5fversioningannotation_5',['udpa_annotations_VersioningAnnotation',['../structudpa__annotations___versioning_annotation.html',1,'']]],
  ['uintselector_6',['UintSelector',['../structgrpc__core_1_1_uint_selector.html',1,'grpc_core']]],
  ['uintselector_3c_2016_20_3e_7',['UintSelector&lt; 16 &gt;',['../structgrpc__core_1_1_uint_selector_3_0116_01_4.html',1,'grpc_core']]],
  ['uintselector_3c_2032_20_3e_8',['UintSelector&lt; 32 &gt;',['../structgrpc__core_1_1_uint_selector_3_0132_01_4.html',1,'grpc_core']]],
  ['uintselector_3c_2064_20_3e_9',['UintSelector&lt; 64 &gt;',['../structgrpc__core_1_1_uint_selector_3_0164_01_4.html',1,'grpc_core']]],
  ['uintselector_3c_208_20_3e_10',['UintSelector&lt; 8 &gt;',['../structgrpc__core_1_1_uint_selector_3_018_01_4.html',1,'grpc_core']]],
  ['unaryasyncbenchmarkclient_11',['UnaryAsyncBenchmarkClient',['../classbenchmark__client_1_1_unary_async_benchmark_client.html',1,'benchmark_client.UnaryAsyncBenchmarkClient'],['../classtests_1_1qps_1_1benchmark__client_1_1_unary_async_benchmark_client.html',1,'tests.qps.benchmark_client.UnaryAsyncBenchmarkClient']]],
  ['unarycall_12',['UnaryCall',['../class_grpc_1_1_unary_call.html',1,'Grpc']]],
  ['unarystream_13',['UnaryStream',['../classgrpc__testing_1_1__channel_1_1__multi__callable_1_1_unary_stream.html',1,'grpc_testing::_channel::_multi_callable']]],
  ['unarystreamcall_14',['UnaryStreamCall',['../classgrpc_1_1aio_1_1__base__call_1_1_unary_stream_call.html',1,'grpc.aio._base_call.UnaryStreamCall'],['../classgrpc_1_1aio_1_1__call_1_1_unary_stream_call.html',1,'grpc.aio._call.UnaryStreamCall']]],
  ['unarystreamcallresponseiterator_15',['UnaryStreamCallResponseIterator',['../classgrpc_1_1aio_1_1__interceptor_1_1_unary_stream_call_response_iterator.html',1,'grpc::aio::_interceptor']]],
  ['unarystreamchannelrpc_16',['UnaryStreamChannelRpc',['../classgrpc__testing_1_1_unary_stream_channel_rpc.html',1,'grpc_testing']]],
  ['unarystreamclientinterceptor_17',['UnaryStreamClientInterceptor',['../classgrpc_1_1aio_1_1__interceptor_1_1_unary_stream_client_interceptor.html',1,'grpc.aio._interceptor.UnaryStreamClientInterceptor'],['../classgrpc_1_1_unary_stream_client_interceptor.html',1,'grpc.UnaryStreamClientInterceptor']]],
  ['unarystreammulticallable_18',['UnaryStreamMultiCallable',['../classgrpc_1_1aio_1_1__base__channel_1_1_unary_stream_multi_callable.html',1,'grpc.aio._base_channel.UnaryStreamMultiCallable'],['../classgrpc_1_1aio_1_1__channel_1_1_unary_stream_multi_callable.html',1,'grpc.aio._channel.UnaryStreamMultiCallable'],['../classgrpc_1_1framework_1_1interfaces_1_1face_1_1face_1_1_unary_stream_multi_callable.html',1,'grpc.framework.interfaces.face.face.UnaryStreamMultiCallable'],['../classgrpc_1_1_unary_stream_multi_callable.html',1,'grpc.UnaryStreamMultiCallable']]],
  ['unarystreamserverrpc_19',['UnaryStreamServerRpc',['../classgrpc__testing_1_1__server_1_1__server__rpc_1_1_unary_stream_server_rpc.html',1,'grpc_testing._server._server_rpc.UnaryStreamServerRpc'],['../classgrpc__testing_1_1_unary_stream_server_rpc.html',1,'grpc_testing.UnaryStreamServerRpc']]],
  ['unarysyncbenchmarkclient_20',['UnarySyncBenchmarkClient',['../classtests_1_1qps_1_1benchmark__client_1_1_unary_sync_benchmark_client.html',1,'tests::qps::benchmark_client']]],
  ['unaryunary_21',['UnaryUnary',['../classgrpc__testing_1_1__channel_1_1__multi__callable_1_1_unary_unary.html',1,'grpc_testing::_channel::_multi_callable']]],
  ['unaryunaryaddmetadatainterceptor_22',['UnaryUnaryAddMetadataInterceptor',['../classtests__aio_1_1unit_1_1__metadata__test_1_1_unary_unary_add_metadata_interceptor.html',1,'tests_aio::unit::_metadata_test']]],
  ['unaryunarycall_23',['UnaryUnaryCall',['../classgrpc_1_1aio_1_1__base__call_1_1_unary_unary_call.html',1,'grpc.aio._base_call.UnaryUnaryCall'],['../classgrpc_1_1aio_1_1__call_1_1_unary_unary_call.html',1,'grpc.aio._call.UnaryUnaryCall']]],
  ['unaryunarycallresponse_24',['UnaryUnaryCallResponse',['../classgrpc_1_1aio_1_1__interceptor_1_1_unary_unary_call_response.html',1,'grpc::aio::_interceptor']]],
  ['unaryunarychannelrpc_25',['UnaryUnaryChannelRpc',['../classgrpc__testing_1_1_unary_unary_channel_rpc.html',1,'grpc_testing']]],
  ['unaryunaryclientinterceptor_26',['UnaryUnaryClientInterceptor',['../classgrpc_1_1aio_1_1__interceptor_1_1_unary_unary_client_interceptor.html',1,'grpc.aio._interceptor.UnaryUnaryClientInterceptor'],['../classgrpc_1_1_unary_unary_client_interceptor.html',1,'grpc.UnaryUnaryClientInterceptor']]],
  ['unaryunarymulticallable_27',['UnaryUnaryMultiCallable',['../classgrpc_1_1aio_1_1__base__channel_1_1_unary_unary_multi_callable.html',1,'grpc.aio._base_channel.UnaryUnaryMultiCallable'],['../classgrpc_1_1aio_1_1__channel_1_1_unary_unary_multi_callable.html',1,'grpc.aio._channel.UnaryUnaryMultiCallable'],['../classgrpc_1_1framework_1_1interfaces_1_1face_1_1face_1_1_unary_unary_multi_callable.html',1,'grpc.framework.interfaces.face.face.UnaryUnaryMultiCallable'],['../classgrpc_1_1_unary_unary_multi_callable.html',1,'grpc.UnaryUnaryMultiCallable']]],
  ['unaryunaryserverrpc_28',['UnaryUnaryServerRpc',['../classgrpc__testing_1_1__server_1_1__server__rpc_1_1_unary_unary_server_rpc.html',1,'grpc_testing._server._server_rpc.UnaryUnaryServerRpc'],['../classgrpc__testing_1_1_unary_unary_server_rpc.html',1,'grpc_testing.UnaryUnaryServerRpc']]],
  ['unimplementedasyncrequest_29',['UnimplementedAsyncRequest',['../classgrpc_1_1_server_1_1_unimplemented_async_request.html',1,'_base_server::Server']]],
  ['unimplementedasyncresponse_30',['UnimplementedAsyncResponse',['../classgrpc_1_1_server_1_1_unimplemented_async_response.html',1,'_base_server::Server']]],
  ['unimplementedserviceclient_31',['UnimplementedServiceClient',['../class_grpc_1_1_testing_1_1_unimplemented_service_client.html',1,'Grpc::Testing']]],
  ['unimplementedservicestub_32',['UnimplementedServiceStub',['../class_grpc_1_1_testing_1_1_unimplemented_service_stub.html',1,'Grpc::Testing']]],
  ['uniqueptrwithbitset_33',['UniquePtrWithBitset',['../classgrpc__core_1_1_unique_ptr_with_bitset.html',1,'grpc_core']]],
  ['uniqueptrwithbitset_3c_20grpc_5fcore_3a_3ahpackparseresult_2c_201_20_3e_34',['UniquePtrWithBitset&lt; grpc_core::HpackParseResult, 1 &gt;',['../classgrpc__core_1_1_unique_ptr_with_bitset.html',1,'grpc_core']]],
  ['uniquetypename_35',['UniqueTypeName',['../classgrpc__core_1_1_unique_type_name.html',1,'grpc_core']]],
  ['unknownaction_36',['UnknownAction',['../structgrpc__core_1_1_xds_route_config_resource_1_1_route_1_1_unknown_action.html',1,'grpc_core::XdsRouteConfigResource::Route']]],
  ['unknownmap_37',['UnknownMap',['../classgrpc__core_1_1metadata__detail_1_1_unknown_map.html',1,'grpc_core::metadata_detail']]],
  ['unrefcalldestroy_38',['UnrefCallDestroy',['../structgrpc__core_1_1_unref_call_destroy.html',1,'grpc_core']]],
  ['unrefcalldtor_39',['UnrefCallDtor',['../structgrpc__core_1_1_unref_call_dtor.html',1,'grpc_core']]],
  ['unrefdelete_40',['UnrefDelete',['../structgrpc__core_1_1_unref_delete.html',1,'grpc_core']]],
  ['unrefdestroy_41',['UnrefDestroy',['../structgrpc__core_1_1arena__detail_1_1_unref_destroy.html',1,'grpc_core::arena_detail']]],
  ['unrefnodelete_42',['UnrefNoDelete',['../structgrpc__core_1_1_unref_no_delete.html',1,'grpc_core']]],
  ['unstartedcalldestination_43',['UnstartedCallDestination',['../classgrpc__core_1_1_unstarted_call_destination.html',1,'grpc_core']]],
  ['unstartedcallhandler_44',['UnstartedCallHandler',['../classgrpc__core_1_1_unstarted_call_handler.html',1,'grpc_core']]],
  ['unwakeable_45',['Unwakeable',['../structgrpc__core_1_1promise__detail_1_1_unwakeable.html',1,'grpc_core::promise_detail']]],
  ['updateargs_46',['UpdateArgs',['../structgrpc__core_1_1_load_balancing_policy_1_1_update_args.html',1,'grpc_core::LoadBalancingPolicy']]],
  ['uri_47',['URI',['../classgrpc__core_1_1_u_r_i.html',1,'grpc_core']]],
  ['urlexternalaccountcredentials_48',['UrlExternalAccountCredentials',['../classgrpc__core_1_1_url_external_account_credentials.html',1,'grpc_core']]],
  ['usageerror_49',['UsageError',['../classgrpc_1_1experimental_1_1_usage_error.html',1,'grpc::experimental']]],
  ['useragentmetadata_50',['UserAgentMetadata',['../structgrpc__core_1_1_user_agent_metadata.html',1,'grpc_core']]],
  ['utilitytest_51',['UtilityTest',['../classtests_1_1unit_1_1__utilities__test_1_1_utility_test.html',1,'tests::unit::_utilities_test']]]
];
